#######################################################################
# SConscript for xorg state_tracker

Import('*')

if 'xorg' in env['statetrackers']:

    env = env.Clone()

    env.Append(CPPPATH = [
	'#/src/mesa',
    ])

    env.ParseConfig('pkg-config --cflags --libs xorg-server')

    st_xorg = env.ConvenienceLibrary(
	target = 'st_xorg',
	source = [ 'xorg_composite.c',
		'xorg_crtc.c',
		'xorg_dri2.c',
		'xorg_driver.c',
		'xorg_exa.c',
		'xorg_exa_tgsi.c',
		'xorg_output.c',
		]
    )
    Export('st_xorg')
