Import('*')

if not env['GLUT']:
    Return()

env = env.Clone()

env.Prepend(CPPPATH = [
	'../util',
])

env.Prepend(LIBS = [
	util,
	'$GLUT_LIB'
])

if env['platform'] == 'windows':
    env.Append(CPPDEFINES = ['NOMINMAX'])
    env.Prepend(LIBS = ['winmm'])

progs = [
	'arbfplight',
	'arbfslight',
	'arbocclude',
	'bounce',
	'clearspd',
	'copypix',
	'cubemap',
	'drawpix',
	'engine',
	'fbo_firecube',
	'fire',
	'fogcoord',
	'fplight',
	'fslight',
	'gamma',
	'gearbox',
	'gears',
	'geartrain',
	'glinfo',
	'gloss',
	'glslnoise',
	'gltestperf',
	'glutfx',
	'isosurf',
	'ipers',
	'lodbias',
	'morph3d',
	'multiarb',
	'paltex',
	'pointblast',
	'ray',
	'readpix',
	'reflect',
	'renormal',
	'shadowtex',
	'singlebuffer',
	'streaming_rect',
	'spectex',
	'spriteblast',
	'stex3d',
	'teapot',
	'terrain',
	'tessdemo',
	'texcyl',
	'texdown',
	'texenv',
	'texobj',
	'textures',
	'trispd',
	'tunnel',
	'tunnel2',
	'vao_demo',
	'winpos',
]

for prog in progs:
    env.Program(
        target = prog,
        source = prog + '.c',
    )
    
env.Program(
    target = 'rain',
    source = [
        'rain.cxx',
        'particles.cxx',
    ]
)
