Import('*')

if not 'r300' in env['drivers']:
    print 'warning: r300 pipe driver not built skipping r300_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_radeon')

env.Append(CPPDEFINES = ['GALLIUM_RBUG', 'GALLIUM_TRACE', 'GALLIUM_GALAHAD'])

env.Prepend(LIBS = [
    st_dri,
    radeonwinsys,
    r300,
    galahad,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

env.SharedLibrary(
    target ='r300_dri.so',
    source = 'target.c',
    SHLIBPREFIX = '',
)
