Import('env')

env = env.Clone()

util = env.StaticLibrary(
    target = ['util'],
    source = [
        'readtex.c',
        'trackball.c',
        'showbuffer.c',
        'shaderutil.c',
    ],
)

Export('util')
