Import('*')

env = drienv.Clone()

env.Append(CPPPATH = [
	'../intel',
	'server'
])

#MINIGLX_SOURCES = server/intel_dri.c

pipe_drivers = [
	softpipe,
	i915simple
]

DRIVER_SOURCES = [
	'intel_winsys_pipe.c',
	'intel_winsys_softpipe.c',
	'intel_winsys_i915.c',
	'intel_batchbuffer.c',
	'intel_swapbuffers.c',
	'intel_context.c',
	'intel_lock.c',
	'intel_screen.c',
	'intel_batchpool.c',
]

sources = \
	COMMON_GALLIUM_SOURCES + \
	COMMON_BM_SOURCES + \
	DRIVER_SOURCES

# DRIVER_DEFINES = -I../intel $(shell pkg-config libdrm --atleast-version=2.3.1 \
#				&& echo "-DDRM_VBLANK_FLIP=DRM_VBLANK_FLIP")

env.SharedLibrary(
	target ='i915tex_dri.so',
	source = sources,
	LIBS = pipe_drivers + env['LIBS'],
)