#######################################################################
# SConscript for xlib winsys


Import('*')

env = env.Clone()

env.Append(CPPPATH = [
    '#/src/gallium/include',
    '#/src/gallium/auxiliary',
])

ws_null = env.ConvenienceLibrary(
    target = 'ws_null',
    source = env.ParseSourceList('Makefile.sources', 'C_SOURCES'),
)
env.Alias('ws_null', ws_null)
Export('ws_null')
