Import('*')

if env['platform'] not in ['linux']:
    Return()

env = env.Clone()

env.AppendUnique(CPPPATH = [
    '#/src/gallium/winsys/g3dvl',
])

XvMCapi = env.StaticLibrary(
    target = 'XvMCapi',
    source = [
        'block.c',
        'surface.c',
        'context.c',
        'subpicture.c',
        'attributes.c',
    ],
)
