#######################################################################
# SConscript for xlib winsys

Import('*')

env = env.Clone()

env.Prepend(LIBS = [
    ws_xlib,
    trace,
    rbug,
    identity,
#    gallium,
])

env.Prepend(LIBS = env['X11_LIBS'])

env.Append(CPPPATH = [
    '#src/gallium/drivers',
    '#src/gallium/include/state_tracker',
])

sources = [
    'graw_xlib.c',
    graw_util
]

if True:
    env.Append(CPPDEFINES = 'GALLIUM_SOFTPIPE')
    env.Prepend(LIBS = [softpipe])

if env['llvm']:
    env.Append(CPPDEFINES = 'GALLIUM_LLVMPIPE')
    env.Prepend(LIBS = [llvmpipe])

# Need this for trace, identity drivers referenced by
# gallium_wrap_screen().
#
env.Prepend(LIBS = [gallium])

# TODO: write a wrapper function http://www.scons.org/wiki/WrapperFunctions
graw = env.SharedLibrary(
    target ='graw',
    source = sources,
)

graw = env.InstallSharedLibrary(graw, version=(1, 0))

env.Alias('graw-xlib', graw)
