TOP = ../../../../..
include $(TOP)/configs/current

LIBNAME = swdrm

C_SOURCES = \
	soft_screen.c \
	wrapper_sw_winsys.c \
	sw_drm_api.c

LIBRARY_INCLUDES =

LIBRARY_DEFINES = -DGALLIUM_SOFTPIPE

include ../../../Makefile.template
