#src/glsl/pp/Makefile

TOP = ../../..

include $(TOP)/configs/current

LIBNAME = glslpp

C_SOURCES = \
	sl_pp_context.c \
	sl_pp_define.c \
	sl_pp_dict.c \
	sl_pp_error.c \
	sl_pp_expression.c \
	sl_pp_extension.c \
	sl_pp_if.c \
	sl_pp_line.c \
	sl_pp_macro.c \
	sl_pp_pragma.c \
	sl_pp_process.c \
	sl_pp_purify.c \
	sl_pp_token.c \
	sl_pp_token_util.c \
	sl_pp_version.c

include ../Makefile.template

