Import('*')

if env['platform'] not in ['windows']:
    Return()

env = env.Clone()

glsl = env.StaticLibrary(
    target = 'glsl',
    source = [
        'sl_pp_context.c',
        'sl_pp_define.c',
        'sl_pp_error.c',
        'sl_pp_expression.c',
        'sl_pp_extension.c',
        'sl_pp_if.c',
        'sl_pp_macro.c',
        'sl_pp_pragma.c',
        'sl_pp_process.c',
        'sl_pp_purify.c',
        'sl_pp_token.c',
        'sl_pp_version.c',
    ],
)
Export('glsl')
