Import('*')

if env['platform'] not in ['windows']:
    Return()

env = env.Clone()

glsl = env.StaticLibrary(
    target = 'glsl',
    source = [
        'sl_pp_purify.c',
        'sl_pp_token.c',
    ],
)
Export('glsl')
