TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = i965

C_SOURCES = \
	brw_cc.c \
	brw_clip.c \
	brw_clip_line.c \
	brw_clip_point.c \
	brw_clip_state.c \
	brw_clip_tri.c \
	brw_clip_unfilled.c \
	brw_clip_util.c \
	brw_context.c \
	brw_curbe.c \
	brw_disasm.c \
	brw_draw.c \
	brw_draw_upload.c \
	brw_eu.c \
	brw_eu_debug.c \
	brw_eu_emit.c \
	brw_eu_util.c \
	brw_gs.c \
	brw_gs_emit.c \
	brw_gs_state.c \
	brw_misc_state.c \
	brw_pipe_blend.c \
	brw_pipe_depth.c \
	brw_pipe_fb.c \
	brw_pipe_query.c \
	brw_pipe_shader.c \
	brw_pipe_flush.c \
	brw_pipe_misc.c \
	brw_pipe_sampler.c \
	brw_pipe_vertex.c \
	brw_pipe_clear.c \
	brw_pipe_rast.c \
	brw_sf.c \
	brw_sf_emit.c \
	brw_sf_state.c \
	brw_state_batch.c \
	brw_state_debug.c \
	brw_state_cache.c \
	brw_state_upload.c \
	brw_structs_dump.c \
	brw_swtnl.c \
	brw_urb.c \
	brw_util.c \
	brw_vs.c \
	brw_vs_emit.c \
	brw_vs_state.c \
	brw_vs_surface_state.c \
	brw_wm.c \
	brw_wm_debug.c \
	brw_wm_emit.c \
	brw_wm_fp.c \
	brw_wm_iz.c \
	brw_wm_pass0.c \
	brw_wm_pass1.c \
	brw_wm_pass2.c \
	brw_wm_sampler_state.c \
	brw_wm_state.c \
	brw_wm_surface_state.c \
	brw_screen.c \
	brw_screen_buffers.c \
	brw_screen_tex_layout.c \
	brw_screen_texture.c \
	brw_screen_surface.c \
	brw_batchbuffer.c \
	brw_winsys_debug.c \
	intel_decode.c

include ../../Makefile.template
