TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = tgsi

C_SOURCES = \
	tgsi_build.c \
	tgsi_dump.c \
	tgsi_exec.c \
	tgsi_info.c \
	tgsi_iterate.c \
	tgsi_parse.c \
	tgsi_scan.c \
	tgsi_sse2.c \
	tgsi_transform.c \
	tgsi_util.c

include ../../Makefile.template

symlinks:

