Import('*')

tgsi = env.ConvenienceLibrary(
	target = 'tgsi',
	source = [
		'tgsi_build.c',
		'tgsi_dump.c',
		'tgsi_dump_c.c',
		'tgsi_exec.c',
		'tgsi_info.c',
		'tgsi_iterate.c',
		'tgsi_parse.c',
		'tgsi_sanity.c',
		'tgsi_scan.c',
		'tgsi_sse2.c',
		'tgsi_text.c',
		'tgsi_transform.c',
		'tgsi_util.c',
	])

auxiliaries.insert(0, tgsi)
