Import('*')

if not 'r300' in env['drivers']:
    print 'warning: r300 pipe driver not built skipping radeong_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_radeon')

drivers = [
    trace,
    softpipe,
    r300
]

env.SharedLibrary(
    target ='radeon_dri.so',
    source = COMMON_GALLIUM_SOURCES,
    LIBS = st_dri + radeonwinsys + mesa + drivers + gallium + env['LIBS'],
)
