Import('*')

if not 'r300' in env['drivers']:
    print 'warning: r300 pipe driver not built skipping radeong_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_radeon')

env.Prepend(LIBS = [
    st_dri,
    radeonwinsys,
    r300,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

env.SharedLibrary(
    target ='radeon_dri.so',
    source = 'dummy.c',
    SHLIBPREFIX = '',
)
