Import('*')

env = env.Clone()

softpipe = env.ConvenienceLibrary(
	target = 'softpipe',
	source = [
		'sp_fs_exec.c',
		'sp_fs_sse.c',
		'sp_fs_llvm.c',
		'sp_clear.c',
		'sp_context.c',
		'sp_draw_arrays.c',
		'sp_flush.c',
		'sp_prim_setup.c',
		'sp_prim_vbuf.c',
		'sp_setup.c',
		'sp_quad_alpha_test.c',
		'sp_quad_blend.c',
		'sp_quad.c',
		'sp_quad_colormask.c',
		'sp_quad_coverage.c',
		'sp_quad_depth_test.c',
		'sp_quad_earlyz.c',
		'sp_quad_fs.c',
		'sp_quad_occlusion.c',
		'sp_quad_output.c',
		'sp_quad_stencil.c',
		'sp_quad_stipple.c',
		'sp_query.c',
		'sp_screen.c',
		'sp_state_blend.c',
		'sp_state_clip.c',
		'sp_state_derived.c',
		'sp_state_fs.c',
		'sp_state_rasterizer.c',
		'sp_state_sampler.c',
		'sp_state_surface.c',
		'sp_state_vertex.c',
		'sp_surface.c',
		'sp_tex_sample.c',
		'sp_texture.c',
		'sp_tile_cache.c',
	])

Export('softpipe')