Import('*')

env = env.Clone()


softpipe = env.ConvenienceLibrary(
	target = 'softpipe',
	source = env.ParseSourceList('Makefile.sources', 'C_SOURCES')
	)

env.Alias('softpipe', softpipe)

Export('softpipe')
