Import('*')

env = drienv.Clone()

env.Append(CPPPATH = [
    '#/src/gallium/winsys/sw/dri',
])

env.Prepend(LIBS = [
    st_drisw,
    ws_dri,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_SW_OBJECTS
])

if True:
    env.Append(CPPDEFINES = [
        'GALLIUM_SOFTPIPE',
        'GALLIUM_RBUG',
        'GALLIUM_TRACE',
    ])
    env.Prepend(LIBS = [softpipe])

if env['llvm']:
    env.Append(CPPDEFINES = 'GALLIUM_LLVMPIPE')
    env.Prepend(LIBS = [llvmpipe])

swrastg_sources = [
    'swrast_drm_api.c'
]

module = env.LoadableModule(
    target ='swrastg_dri.so',
    source = swrastg_sources,
    SHLIBPREFIX = '',
)

env.Alias('dri-swrast', module)
