Import('*')

env = drienv.Clone()

env.Append(CPPPATH = [
    '#/src/gallium/winsys/sw/dri',
])

env.Prepend(LIBS = [
    st_drisw,
    ws_dri,
    noop,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_SW_OBJECTS
])

env.Prepend(LIBS = [noop])

swrastg_sources = [
    'swrast_drm_api.c'
]

module = env.LoadableModule(
    target ='noop_dri.so',
    source = swrastg_sources,
    SHLIBPREFIX = '',
)

env.Alias('dri-noop', module)
