#!/bin/sh

for test in *.c; do
    echo "Testing $test"
    ../glcpp < $test > $test.out
    gcc -E $test -o $test.gcc
    grep -v '^#' < $test.gcc > $test.expected
    diff -B -w -u $test.expected $test.out
done
