Import('*')

if not 'r600' in env['drivers']:
    print 'warning: r600 pipe driver not built skipping r600_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_radeon')

env.Append(CPPDEFINES = ['GALLIUM_RBUG', 'GALLIUM_TRACE'])

env.Prepend(LIBS = [
    st_dri,
    r600winsys,
    r600,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

env.SharedLibrary(
    target ='r600_dri.so',
    source = 'target.c',
    SHLIBPREFIX = '',
)
