TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = trace

C_SOURCES = \
	tr_context.c \
	tr_dump.c \
	tr_screen.c \
	tr_state.c \
	tr_texture.c \
	tr_winsys.c

include ../../Makefile.template
