TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = trace

C_SOURCES = \
	tr_context.c \
	tr_dump.c \
	tr_dump_state.c \
	tr_screen.c \
	tr_texture.c

include ../../Makefile.template

# FIXME: Remove when this driver is converted to automake.
all: default
