Import('*')

env = env.Clone()

trace = env.ConvenienceLibrary(
    target = 'trace',
    source = [
        'tr_buffer.c',
        'tr_context.c',
        'tr_drm.c',
        'tr_dump.c',
        'tr_dump_state.c',
        'tr_screen.c',
        'tr_state.c',
        'tr_rbug.c',
        'tr_texture.c',
    ])

Export('trace')
