Import('*')

env = env.Clone()

trace = env.ConvenienceLibrary(
    target = 'trace',
    source = env.ParseSourceList('Makefile.sources', 'C_SOURCES')
    )

env.Alias('trace', trace)

Export('trace')
