Import('*')

env = env.Clone()

trace = env.ConvenienceLibrary(
    target = 'trace',
    source = [
        'tr_context.c',
        'tr_dump.c',
        'tr_screen.c',
        'tr_state.c',
        'tr_texture.c',
        'tr_winsys.c',
    ])

Export('trace')