Import('*')

env.CodeGenerate(
	target = 'u_indices_gen.c', 
	script = 'u_indices_gen.py', 
	source = [],
	command = 'python $SCRIPT > $TARGET'
)

indices = env.ConvenienceLibrary(
	target = 'indices',
	source = [
#               'u_indices.c',
               'u_indices_gen.c',
	])

auxiliaries.insert(0, indices)
