Import('*')

from sys import executable as python_cmd

env.CodeGenerate(
	target = 'u_indices_gen.c', 
	script = 'u_indices_gen.py', 
	source = [],
	command = python_cmd + ' $SCRIPT > $TARGET'
)

env.CodeGenerate(
	target = 'u_unfilled_gen.c', 
	script = 'u_unfilled_gen.py', 
	source = [],
	command = python_cmd + ' $SCRIPT > $TARGET'
)

indices = env.ConvenienceLibrary(
	target = 'indices',
	source = [
#               'u_indices.c',
#               'u_unfilled_indices.c',
               'u_indices_gen.c',
               'u_unfilled_gen.c',
	])

auxiliaries.insert(0, indices)
