C_SOURCES := \
	fd3_blend.c \
	fd3_compiler.c \
	fd3_context.c \
	fd3_draw.c \
	fd3_emit.c \
	fd3_gmem.c \
	fd3_program.c \
	fd3_rasterizer.c \
	fd3_screen.c \
	fd3_texture.c \
	fd3_util.c \
	fd3_zsa.c \
	disasm-a3xx.c \
	ir-a3xx.c
