import os.path

Import('*')

if env['platform'] == 'linux':

    env = env.Clone()
    
    env.Tool('python')
    
    env.ParseConfig('pkg-config --cflags --libs libdrm')
    
    env.Prepend(CPPPATH = [
        '#src/gallium/state_trackers/python',
        '../core',
    ])
    
    drivers = [
        softpipe,
        radeon,
        trace,
    ]
    
    sources = [
        'radeon_hardpipe_winsys.c',
        'xf86dri.c',
    ]
    
    env.SharedLibrary(
        target ='_gallium',
        source = sources,
        LIBS = [pyst] + drivers + gallium + env['LIBS'],
    )
