TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv04

C_SOURCES = \
	nv04_surface_2d.c \
	nv04_clear.c \
	nv04_context.c \
	nv04_fragprog.c \
	nv04_fragtex.c \
	nv04_miptree.c \
	nv04_prim_vbuf.c \
	nv04_screen.c \
	nv04_state.c \
	nv04_state_emit.c \
	nv04_surface.c \
	nv04_transfer.c \
	nv04_vbo.c

include ../../Makefile.template
