
TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = rtasm

DRIVER_SOURCES = \
	rtasm_execmem.c \
	rtasm_x86sse.c

C_SOURCES = \
	$(DRIVER_SOURCES)

ASM_SOURCES = 

include ../../Makefile.template

symlinks:

