
TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = rtasm

DRIVER_SOURCES = \
	execmem.c \
	x86sse.c \
	mm.c

C_SOURCES = \
	$(DRIVER_SOURCES)

ASM_SOURCES = 

include ../../Makefile.template

symlinks:

