TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv10

C_SOURCES = \
	nv10_clear.c \
	nv10_context.c \
	nv10_fragprog.c \
	nv10_fragtex.c \
	nv10_miptree.c \
	nv10_prim_vbuf.c \
	nv10_screen.c \
	nv10_state.c \
	nv10_state_emit.c \
	nv10_surface.c \
	nv10_transfer.c \
	nv10_vbo.c

include ../../Makefile.template
