
TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = failover

DRIVER_SOURCES = \
	fo_state.c \
	fo_state_emit.c \
	fo_context.c 

C_SOURCES = \
	$(COMMON_SOURCES) \
	$(DRIVER_SOURCES)

ASM_SOURCES = 

include ../Makefile.template

symlinks:

