TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = rbug

C_SOURCES = \
	rbug_connection.c \
	rbug_core.c \
	rbug_texture.c \
	rbug_context.c \
	rbug_shader.c \
	rbug_demarshal.c

include ../../Makefile.template
