#######################################################################
# SConscript for egl state_tracker

Import('*')

if 'egl' in env['statetrackers']:

    env = env.Clone()

    env.Append(CPPPATH = [
	'#/src/egl/main',
	'#/src/gallium/winsys/sw',
	'.',
    ])
    env.Append(CPPDEFINES = [
	'HAVE_GDI_BACKEND',
    ])

    common_sources = [
        'common/egl_g3d.c',
        'common/egl_g3d_api.c',
        'common/egl_g3d_image.c',
        'common/egl_g3d_st.c',
        'common/egl_g3d_sync.c',
        'common/native_helper.c',
    ]

    gdi_sources = common_sources + [
        'gdi/native_gdi.c',
    ]

    st_egl_gdi = env.ConvenienceLibrary(
	target = 'st_egl_gdi',
	source = gdi_sources,
    )
    Export('st_egl_gdi')
