Import('*')

SConscript('osmesa/SConscript')

if env['x11']:
    SConscript('x11/SConscript')

if env['dri']:
    SConscript([
        'dri/common/xmlpool/SConscript',
        'dri/common/SConscript',
    ])

if env['platform'] == 'windows':
    SConscript('windows/gdi/SConscript')

if env['platform'] == 'haiku':
    SConscript('haiku/swrast/SConscript')
