Import('*')

SConscript('osmesa/SConscript')

if env['x11']:
    SConscript('x11/SConscript')

if env['drm']:
    SConscript('dri/common/xmlpool/SConscript')

if env['platform'] == 'windows':
    SConscript('windows/gdi/SConscript')
