Import('*')

env = env.Clone()

env.Prepend(LIBS = [gallium])

progs = [
    'u_format_test'
]

for prog in progs:
    prog = env.Program(
        target = prog,
        source = prog + '.c',
    )

    # http://www.scons.org/wiki/UnitTests
    test_alias = env.Alias('unit', [prog], prog[0].abspath)
    AlwaysBuild(test_alias)

