Import('*')

env = drienv.Clone()

radeon_sources = [
    'radeon_buffer.c',
    'radeon_drm.c',
    'radeon_r300.c',
]

env.Append(CPPPATH = '#/src/gallium/drivers/r300')

radeonwinsys = env.ConvenienceLibrary(
    target ='radeonwinsys',
    source = radeon_sources,
)

Export('radeonwinsys')
