Import('*')

if progs_env['platform'] != 'windows':
    Return()

progs = [
    'sharedtex_mt',
    'wglthreads',
]

for prog in progs:
    progs_env.Program(
        target = prog,
        source = prog + '/' + prog + '.c',
    )

progs_env.Program('wglinfo', ['wglinfo.c'])
