/* $XFree86: xc/lib/GL/glx/indirect_wrap.h,v 1.4 2003/09/28 20:15:04 alanh Exp $ */
/**************************************************************************

Copyright 1998-1999 Precision Insight, Inc., Cedar Park, Texas.
All Rights Reserved.

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sub license, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice (including the
next paragraph) shall be included in all copies or substantial portions
of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.
IN NO EVENT SHALL PRECISION INSIGHT AND/OR ITS SUPPLIERS BE LIABLE FOR
ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

**************************************************************************/

/*
 * Authors:
 *   Kevin E. Martin <kevin@precisioninsight.com>
 *
 */

/* NOTE: This file could be automatically generated */

#ifndef _INDIRECT_WRAP_H_
#define _INDIRECT_WRAP_H_

#define glAccum __indirect_glAccum
#define glAlphaFunc __indirect_glAlphaFunc
#define glAreTexturesResident __indirect_glAreTexturesResident
#define glArrayElement __indirect_glArrayElement
#define glBegin __indirect_glBegin
#define glBindTexture __indirect_glBindTexture
#define glBitmap __indirect_glBitmap
#define glBlendFunc __indirect_glBlendFunc
#define glCallList __indirect_glCallList
#define glCallLists __indirect_glCallLists
#define glClear __indirect_glClear
#define glClearAccum __indirect_glClearAccum
#define glClearColor __indirect_glClearColor
#define glClearDepth __indirect_glClearDepth
#define glClearIndex __indirect_glClearIndex
#define glClearStencil __indirect_glClearStencil
#define glClipPlane __indirect_glClipPlane
#define glColor3b __indirect_glColor3b
#define glColor3bv __indirect_glColor3bv
#define glColor3d __indirect_glColor3d
#define glColor3dv __indirect_glColor3dv
#define glColor3f __indirect_glColor3f
#define glColor3fv __indirect_glColor3fv
#define glColor3i __indirect_glColor3i
#define glColor3iv __indirect_glColor3iv
#define glColor3s __indirect_glColor3s
#define glColor3sv __indirect_glColor3sv
#define glColor3ub __indirect_glColor3ub
#define glColor3ubv __indirect_glColor3ubv
#define glColor3ui __indirect_glColor3ui
#define glColor3uiv __indirect_glColor3uiv
#define glColor3us __indirect_glColor3us
#define glColor3usv __indirect_glColor3usv
#define glColor4b __indirect_glColor4b
#define glColor4bv __indirect_glColor4bv
#define glColor4d __indirect_glColor4d
#define glColor4dv __indirect_glColor4dv
#define glColor4f __indirect_glColor4f
#define glColor4fv __indirect_glColor4fv
#define glColor4i __indirect_glColor4i
#define glColor4iv __indirect_glColor4iv
#define glColor4s __indirect_glColor4s
#define glColor4sv __indirect_glColor4sv
#define glColor4ub __indirect_glColor4ub
#define glColor4ubv __indirect_glColor4ubv
#define glColor4ui __indirect_glColor4ui
#define glColor4uiv __indirect_glColor4uiv
#define glColor4us __indirect_glColor4us
#define glColor4usv __indirect_glColor4usv
#define glColorMask __indirect_glColorMask
#define glColorMaterial __indirect_glColorMaterial
#define glColorPointer __indirect_glColorPointer
#define glCopyPixels __indirect_glCopyPixels
#define glCopyTexImage1D __indirect_glCopyTexImage1D
#define glCopyTexImage2D __indirect_glCopyTexImage2D
#define glCopyTexSubImage1D __indirect_glCopyTexSubImage1D
#define glCopyTexSubImage2D __indirect_glCopyTexSubImage2D
#define glCullFace __indirect_glCullFace
#define glDeleteLists __indirect_glDeleteLists
#define glDeleteTextures __indirect_glDeleteTextures
#define glDepthFunc __indirect_glDepthFunc
#define glDepthMask __indirect_glDepthMask
#define glDepthRange __indirect_glDepthRange
#define glDisable __indirect_glDisable
#define glDisableClientState __indirect_glDisableClientState
#define glDrawArrays __indirect_glDrawArrays
#define glDrawBuffer __indirect_glDrawBuffer
#define glDrawElements __indirect_glDrawElements
#define glDrawPixels __indirect_glDrawPixels
#define glEdgeFlag __indirect_glEdgeFlag
#define glEdgeFlagPointer __indirect_glEdgeFlagPointer
#define glEdgeFlagv __indirect_glEdgeFlagv
#define glEnable __indirect_glEnable
#define glEnableClientState __indirect_glEnableClientState
#define glEnd __indirect_glEnd
#define glEndList __indirect_glEndList
#define glEvalCoord1d __indirect_glEvalCoord1d
#define glEvalCoord1dv __indirect_glEvalCoord1dv
#define glEvalCoord1f __indirect_glEvalCoord1f
#define glEvalCoord1fv __indirect_glEvalCoord1fv
#define glEvalCoord2d __indirect_glEvalCoord2d
#define glEvalCoord2dv __indirect_glEvalCoord2dv
#define glEvalCoord2f __indirect_glEvalCoord2f
#define glEvalCoord2fv __indirect_glEvalCoord2fv
#define glEvalMesh1 __indirect_glEvalMesh1
#define glEvalMesh2 __indirect_glEvalMesh2
#define glEvalPoint1 __indirect_glEvalPoint1
#define glEvalPoint2 __indirect_glEvalPoint2
#define glFeedbackBuffer __indirect_glFeedbackBuffer
#define glFinish __indirect_glFinish
#define glFlush __indirect_glFlush
#define glFogf __indirect_glFogf
#define glFogfv __indirect_glFogfv
#define glFogi __indirect_glFogi
#define glFogiv __indirect_glFogiv
#define glFrontFace __indirect_glFrontFace
#define glFrustum __indirect_glFrustum
#define glGenLists __indirect_glGenLists
#define glGenTextures __indirect_glGenTextures
#define glGetBooleanv __indirect_glGetBooleanv
#define glGetClipPlane __indirect_glGetClipPlane
#define glGetDoublev __indirect_glGetDoublev
#define glGetError __indirect_glGetError
#define glGetFloatv __indirect_glGetFloatv
#define glGetIntegerv __indirect_glGetIntegerv
#define glGetLightfv __indirect_glGetLightfv
#define glGetLightiv __indirect_glGetLightiv
#define glGetMapdv __indirect_glGetMapdv
#define glGetMapfv __indirect_glGetMapfv
#define glGetMapiv __indirect_glGetMapiv
#define glGetMaterialfv __indirect_glGetMaterialfv
#define glGetMaterialiv __indirect_glGetMaterialiv
#define glGetPixelMapfv __indirect_glGetPixelMapfv
#define glGetPixelMapuiv __indirect_glGetPixelMapuiv
#define glGetPixelMapusv __indirect_glGetPixelMapusv
#define glGetPointerv __indirect_glGetPointerv
#define glGetPolygonStipple __indirect_glGetPolygonStipple
#define glGetString __indirect_glGetString
#define glGetTexEnvfv __indirect_glGetTexEnvfv
#define glGetTexEnviv __indirect_glGetTexEnviv
#define glGetTexGendv __indirect_glGetTexGendv
#define glGetTexGenfv __indirect_glGetTexGenfv
#define glGetTexGeniv __indirect_glGetTexGeniv
#define glGetTexImage __indirect_glGetTexImage
#define glGetTexLevelParameterfv __indirect_glGetTexLevelParameterfv
#define glGetTexLevelParameteriv __indirect_glGetTexLevelParameteriv
#define glGetTexParameterfv __indirect_glGetTexParameterfv
#define glGetTexParameteriv __indirect_glGetTexParameteriv
#define glHint __indirect_glHint
#define glIndexMask __indirect_glIndexMask
#define glIndexPointer __indirect_glIndexPointer
#define glIndexd __indirect_glIndexd
#define glIndexdv __indirect_glIndexdv
#define glIndexf __indirect_glIndexf
#define glIndexfv __indirect_glIndexfv
#define glIndexi __indirect_glIndexi
#define glIndexiv __indirect_glIndexiv
#define glIndexs __indirect_glIndexs
#define glIndexsv __indirect_glIndexsv
#define glIndexub __indirect_glIndexub
#define glIndexubv __indirect_glIndexubv
#define glInitNames __indirect_glInitNames
#define glInterleavedArrays __indirect_glInterleavedArrays
#define glIsEnabled __indirect_glIsEnabled
#define glIsList __indirect_glIsList
#define glIsTexture __indirect_glIsTexture
#define glLightModelf __indirect_glLightModelf
#define glLightModelfv __indirect_glLightModelfv
#define glLightModeli __indirect_glLightModeli
#define glLightModeliv __indirect_glLightModeliv
#define glLightf __indirect_glLightf
#define glLightfv __indirect_glLightfv
#define glLighti __indirect_glLighti
#define glLightiv __indirect_glLightiv
#define glLineStipple __indirect_glLineStipple
#define glLineWidth __indirect_glLineWidth
#define glListBase __indirect_glListBase
#define glLoadIdentity __indirect_glLoadIdentity
#define glLoadMatrixd __indirect_glLoadMatrixd
#define glLoadMatrixf __indirect_glLoadMatrixf
#define glLoadName __indirect_glLoadName
#define glLogicOp __indirect_glLogicOp
#define glMap1d __indirect_glMap1d
#define glMap1f __indirect_glMap1f
#define glMap2d __indirect_glMap2d
#define glMap2f __indirect_glMap2f
#define glMapGrid1d __indirect_glMapGrid1d
#define glMapGrid1f __indirect_glMapGrid1f
#define glMapGrid2d __indirect_glMapGrid2d
#define glMapGrid2f __indirect_glMapGrid2f
#define glMaterialf __indirect_glMaterialf
#define glMaterialfv __indirect_glMaterialfv
#define glMateriali __indirect_glMateriali
#define glMaterialiv __indirect_glMaterialiv
#define glMatrixMode __indirect_glMatrixMode
#define glMultMatrixd __indirect_glMultMatrixd
#define glMultMatrixf __indirect_glMultMatrixf
#define glNewList __indirect_glNewList
#define glNormal3b __indirect_glNormal3b
#define glNormal3bv __indirect_glNormal3bv
#define glNormal3d __indirect_glNormal3d
#define glNormal3dv __indirect_glNormal3dv
#define glNormal3f __indirect_glNormal3f
#define glNormal3fv __indirect_glNormal3fv
#define glNormal3i __indirect_glNormal3i
#define glNormal3iv __indirect_glNormal3iv
#define glNormal3s __indirect_glNormal3s
#define glNormal3sv __indirect_glNormal3sv
#define glNormalPointer __indirect_glNormalPointer
#define glOrtho __indirect_glOrtho
#define glPassThrough __indirect_glPassThrough
#define glPixelMapfv __indirect_glPixelMapfv
#define glPixelMapuiv __indirect_glPixelMapuiv
#define glPixelMapusv __indirect_glPixelMapusv
#define glPixelStoref __indirect_glPixelStoref
#define glPixelStorei __indirect_glPixelStorei
#define glPixelTransferf __indirect_glPixelTransferf
#define glPixelTransferi __indirect_glPixelTransferi
#define glPixelZoom __indirect_glPixelZoom
#define glPointSize __indirect_glPointSize
#define glPolygonMode __indirect_glPolygonMode
#define glPolygonOffset __indirect_glPolygonOffset
#define glPolygonStipple __indirect_glPolygonStipple
#define glPopAttrib __indirect_glPopAttrib
#define glPopClientAttrib __indirect_glPopClientAttrib
#define glPopMatrix __indirect_glPopMatrix
#define glPopName __indirect_glPopName
#define glPrioritizeTextures __indirect_glPrioritizeTextures
#define glPushAttrib __indirect_glPushAttrib
#define glPushClientAttrib __indirect_glPushClientAttrib
#define glPushMatrix __indirect_glPushMatrix
#define glPushName __indirect_glPushName
#define glRasterPos2d __indirect_glRasterPos2d
#define glRasterPos2dv __indirect_glRasterPos2dv
#define glRasterPos2f __indirect_glRasterPos2f
#define glRasterPos2fv __indirect_glRasterPos2fv
#define glRasterPos2i __indirect_glRasterPos2i
#define glRasterPos2iv __indirect_glRasterPos2iv
#define glRasterPos2s __indirect_glRasterPos2s
#define glRasterPos2sv __indirect_glRasterPos2sv
#define glRasterPos3d __indirect_glRasterPos3d
#define glRasterPos3dv __indirect_glRasterPos3dv
#define glRasterPos3f __indirect_glRasterPos3f
#define glRasterPos3fv __indirect_glRasterPos3fv
#define glRasterPos3i __indirect_glRasterPos3i
#define glRasterPos3iv __indirect_glRasterPos3iv
#define glRasterPos3s __indirect_glRasterPos3s
#define glRasterPos3sv __indirect_glRasterPos3sv
#define glRasterPos4d __indirect_glRasterPos4d
#define glRasterPos4dv __indirect_glRasterPos4dv
#define glRasterPos4f __indirect_glRasterPos4f
#define glRasterPos4fv __indirect_glRasterPos4fv
#define glRasterPos4i __indirect_glRasterPos4i
#define glRasterPos4iv __indirect_glRasterPos4iv
#define glRasterPos4s __indirect_glRasterPos4s
#define glRasterPos4sv __indirect_glRasterPos4sv
#define glReadBuffer __indirect_glReadBuffer
#define glReadPixels __indirect_glReadPixels
#define glRectd __indirect_glRectd
#define glRectdv __indirect_glRectdv
#define glRectf __indirect_glRectf
#define glRectfv __indirect_glRectfv
#define glRecti __indirect_glRecti
#define glRectiv __indirect_glRectiv
#define glRects __indirect_glRects
#define glRectsv __indirect_glRectsv
#define glRenderMode __indirect_glRenderMode
#define glRotated __indirect_glRotated
#define glRotatef __indirect_glRotatef
#define glScaled __indirect_glScaled
#define glScalef __indirect_glScalef
#define glScissor __indirect_glScissor
#define glSelectBuffer __indirect_glSelectBuffer
#define glShadeModel __indirect_glShadeModel
#define glStencilFunc __indirect_glStencilFunc
#define glStencilMask __indirect_glStencilMask
#define glStencilOp __indirect_glStencilOp
#define glTexCoord1d __indirect_glTexCoord1d
#define glTexCoord1dv __indirect_glTexCoord1dv
#define glTexCoord1f __indirect_glTexCoord1f
#define glTexCoord1fv __indirect_glTexCoord1fv
#define glTexCoord1i __indirect_glTexCoord1i
#define glTexCoord1iv __indirect_glTexCoord1iv
#define glTexCoord1s __indirect_glTexCoord1s
#define glTexCoord1sv __indirect_glTexCoord1sv
#define glTexCoord2d __indirect_glTexCoord2d
#define glTexCoord2dv __indirect_glTexCoord2dv
#define glTexCoord2f __indirect_glTexCoord2f
#define glTexCoord2fv __indirect_glTexCoord2fv
#define glTexCoord2i __indirect_glTexCoord2i
#define glTexCoord2iv __indirect_glTexCoord2iv
#define glTexCoord2s __indirect_glTexCoord2s
#define glTexCoord2sv __indirect_glTexCoord2sv
#define glTexCoord3d __indirect_glTexCoord3d
#define glTexCoord3dv __indirect_glTexCoord3dv
#define glTexCoord3f __indirect_glTexCoord3f
#define glTexCoord3fv __indirect_glTexCoord3fv
#define glTexCoord3i __indirect_glTexCoord3i
#define glTexCoord3iv __indirect_glTexCoord3iv
#define glTexCoord3s __indirect_glTexCoord3s
#define glTexCoord3sv __indirect_glTexCoord3sv
#define glTexCoord4d __indirect_glTexCoord4d
#define glTexCoord4dv __indirect_glTexCoord4dv
#define glTexCoord4f __indirect_glTexCoord4f
#define glTexCoord4fv __indirect_glTexCoord4fv
#define glTexCoord4i __indirect_glTexCoord4i
#define glTexCoord4iv __indirect_glTexCoord4iv
#define glTexCoord4s __indirect_glTexCoord4s
#define glTexCoord4sv __indirect_glTexCoord4sv
#define glTexCoordPointer __indirect_glTexCoordPointer
#define glTexEnvf __indirect_glTexEnvf
#define glTexEnvfv __indirect_glTexEnvfv
#define glTexEnvi __indirect_glTexEnvi
#define glTexEnviv __indirect_glTexEnviv
#define glTexGend __indirect_glTexGend
#define glTexGendv __indirect_glTexGendv
#define glTexGenf __indirect_glTexGenf
#define glTexGenfv __indirect_glTexGenfv
#define glTexGeni __indirect_glTexGeni
#define glTexGeniv __indirect_glTexGeniv
#define glTexImage1D __indirect_glTexImage1D
#define glTexImage2D __indirect_glTexImage2D
#define glTexParameterf __indirect_glTexParameterf
#define glTexParameterfv __indirect_glTexParameterfv
#define glTexParameteri __indirect_glTexParameteri
#define glTexParameteriv __indirect_glTexParameteriv
#define glTexSubImage1D __indirect_glTexSubImage1D
#define glTexSubImage2D __indirect_glTexSubImage2D
#define glTranslated __indirect_glTranslated
#define glTranslatef __indirect_glTranslatef
#define glVertex2d __indirect_glVertex2d
#define glVertex2dv __indirect_glVertex2dv
#define glVertex2f __indirect_glVertex2f
#define glVertex2fv __indirect_glVertex2fv
#define glVertex2i __indirect_glVertex2i
#define glVertex2iv __indirect_glVertex2iv
#define glVertex2s __indirect_glVertex2s
#define glVertex2sv __indirect_glVertex2sv
#define glVertex3d __indirect_glVertex3d
#define glVertex3dv __indirect_glVertex3dv
#define glVertex3f __indirect_glVertex3f
#define glVertex3fv __indirect_glVertex3fv
#define glVertex3i __indirect_glVertex3i
#define glVertex3iv __indirect_glVertex3iv
#define glVertex3s __indirect_glVertex3s
#define glVertex3sv __indirect_glVertex3sv
#define glVertex4d __indirect_glVertex4d
#define glVertex4dv __indirect_glVertex4dv
#define glVertex4f __indirect_glVertex4f
#define glVertex4fv __indirect_glVertex4fv
#define glVertex4i __indirect_glVertex4i
#define glVertex4iv __indirect_glVertex4iv
#define glVertex4s __indirect_glVertex4s
#define glVertex4sv __indirect_glVertex4sv
#define glVertexPointer __indirect_glVertexPointer
#define glViewport __indirect_glViewport

/* 1.2 */
#define glCopyTexSubImage3D __indirect_glCopyTexSubImage3D
#define glDrawRangeElements __indirect_glDrawRangeElements
#define glTexImage3D __indirect_glTexImage3D
#define glTexSubImage3D __indirect_glTexSubImage3D

/* 1.4 */
#define glMultiDrawArrays __indirect_glMultiDrawArrays
#define glMultiDrawElements __indirect_glMultiDrawElements
#define glBlendFuncSeparate __indirect_glBlendFuncSeparate

/* GL_ARB_imaging */
#define glBlendColor __indirect_glBlendColor
#define glBlendEquation __indirect_glBlendEquation
#define glColorSubTable __indirect_glColorSubTable
#define glColorTable __indirect_glColorTable
#define glColorTableParameterfv __indirect_glColorTableParameterfv
#define glColorTableParameteriv __indirect_glColorTableParameteriv
#define glConvolutionFilter1D __indirect_glConvolutionFilter1D
#define glConvolutionFilter2D __indirect_glConvolutionFilter2D
#define glConvolutionParameterf __indirect_glConvolutionParameterf
#define glConvolutionParameterfv __indirect_glConvolutionParameterfv
#define glConvolutionParameteri __indirect_glConvolutionParameteri
#define glConvolutionParameteriv __indirect_glConvolutionParameteriv
#define glCopyColorSubTable __indirect_glCopyColorSubTable
#define glCopyColorTable __indirect_glCopyColorTable
#define glCopyConvolutionFilter1D __indirect_glCopyConvolutionFilter1D
#define glCopyConvolutionFilter2D __indirect_glCopyConvolutionFilter2D
#define glGetColorTable __indirect_glGetColorTable
#define glGetColorTableParameterfv __indirect_glGetColorTableParameterfv
#define glGetColorTableParameteriv __indirect_glGetColorTableParameteriv
#define glGetConvolutionFilter __indirect_glGetConvolutionFilter
#define glGetConvolutionParameterfv __indirect_glGetConvolutionParameterfv
#define glGetConvolutionParameteriv __indirect_glGetConvolutionParameteriv
#define glGetHistogram __indirect_glGetHistogram
#define glGetHistogramParameterfv __indirect_glGetHistogramParameterfv
#define glGetHistogramParameteriv __indirect_glGetHistogramParameteriv
#define glGetMinmax __indirect_glGetMinmax
#define glGetMinmaxParameterfv __indirect_glGetMinmaxParameterfv
#define glGetMinmaxParameteriv __indirect_glGetMinmaxParameteriv
#define glGetSeparableFilter __indirect_glGetSeparableFilter
#define glHistogram __indirect_glHistogram
#define glMinmax __indirect_glMinmax
#define glResetHistogram __indirect_glResetHistogram
#define glResetMinmax __indirect_glResetMinmax
#define glSeparableFilter2D __indirect_glSeparableFilter2D

/* ARB 1. GL_ARB_multitexture */
#define glActiveTextureARB __indirect_glActiveTextureARB
#define glClientActiveTextureARB __indirect_glClientActiveTextureARB
#define glMultiTexCoord1dARB __indirect_glMultiTexCoord1dARB
#define glMultiTexCoord1dvARB __indirect_glMultiTexCoord1dvARB
#define glMultiTexCoord1fARB __indirect_glMultiTexCoord1fARB
#define glMultiTexCoord1fvARB __indirect_glMultiTexCoord1fvARB
#define glMultiTexCoord1iARB __indirect_glMultiTexCoord1iARB
#define glMultiTexCoord1ivARB __indirect_glMultiTexCoord1ivARB
#define glMultiTexCoord1sARB __indirect_glMultiTexCoord1sARB
#define glMultiTexCoord1svARB __indirect_glMultiTexCoord1svARB
#define glMultiTexCoord2dARB __indirect_glMultiTexCoord2dARB
#define glMultiTexCoord2dvARB __indirect_glMultiTexCoord2dvARB
#define glMultiTexCoord2fARB __indirect_glMultiTexCoord2fARB
#define glMultiTexCoord2fvARB __indirect_glMultiTexCoord2fvARB
#define glMultiTexCoord2iARB __indirect_glMultiTexCoord2iARB
#define glMultiTexCoord2ivARB __indirect_glMultiTexCoord2ivARB
#define glMultiTexCoord2sARB __indirect_glMultiTexCoord2sARB
#define glMultiTexCoord2svARB __indirect_glMultiTexCoord2svARB
#define glMultiTexCoord3dARB __indirect_glMultiTexCoord3dARB
#define glMultiTexCoord3dvARB __indirect_glMultiTexCoord3dvARB
#define glMultiTexCoord3fARB __indirect_glMultiTexCoord3fARB
#define glMultiTexCoord3fvARB __indirect_glMultiTexCoord3fvARB
#define glMultiTexCoord3iARB __indirect_glMultiTexCoord3iARB
#define glMultiTexCoord3ivARB __indirect_glMultiTexCoord3ivARB
#define glMultiTexCoord3sARB __indirect_glMultiTexCoord3sARB
#define glMultiTexCoord3svARB __indirect_glMultiTexCoord3svARB
#define glMultiTexCoord4dARB __indirect_glMultiTexCoord4dARB
#define glMultiTexCoord4dvARB __indirect_glMultiTexCoord4dvARB
#define glMultiTexCoord4fARB __indirect_glMultiTexCoord4fARB
#define glMultiTexCoord4fvARB __indirect_glMultiTexCoord4fvARB
#define glMultiTexCoord4iARB __indirect_glMultiTexCoord4iARB
#define glMultiTexCoord4ivARB __indirect_glMultiTexCoord4ivARB
#define glMultiTexCoord4sARB __indirect_glMultiTexCoord4sARB
#define glMultiTexCoord4svARB __indirect_glMultiTexCoord4svARB

/* ARB 3. ARB_transpose_matrix */

#define glLoadTransposeMatrixdARB __indirect_glLoadTransposeMatrixdARB
#define glLoadTransposeMatrixfARB __indirect_glLoadTransposeMatrixfARB
#define glMultTransposeMatrixdARB __indirect_glMultTransposeMatrixdARB
#define glMultTransposeMatrixfARB __indirect_glMultTransposeMatrixfARB

/* ARB 5. ARB_multisample */

#define glSampleCoverageARB __indirect_glSampleCoverageARB

/* ARB 12. ARB_texture_compression */

/* FIXME: Not yet supported. */

/* ARB 14. ARB_point_parameters / GL 1.4 / NV_point_sprite */

#define glPointParameterfARB __indirect_glPointParameterfARB
#define glPointParameterfvARB __indirect_glPointParameterfvARB
#define glPointParameteri __indirect_glPointParameteri
#define glPointParameteriv __indirect_glPointParameteriv

/* ARB 25. ARB_window_pos */

#define glWindowPos2dARB __indirect_glWindowPos2dARB
#define glWindowPos2fARB __indirect_glWindowPos2fARB
#define glWindowPos2iARB __indirect_glWindowPos2iARB
#define glWindowPos2sARB __indirect_glWindowPos2sARB
#define glWindowPos2dvARB __indirect_glWindowPos2dvARB
#define glWindowPos2fvARB __indirect_glWindowPos2fvARB
#define glWindowPos2ivARB __indirect_glWindowPos2ivARB
#define glWindowPos2svARB __indirect_glWindowPos2svARB
#define glWindowPos3dARB __indirect_glWindowPos3dARB
#define glWindowPos3fARB __indirect_glWindowPos3fARB
#define glWindowPos3iARB __indirect_glWindowPos3iARB
#define glWindowPos3sARB __indirect_glWindowPos3sARB
#define glWindowPos3dvARB __indirect_glWindowPos3dvARB
#define glWindowPos3fvARB __indirect_glWindowPos3fvARB
#define glWindowPos3ivARB __indirect_glWindowPos3ivARB
#define glWindowPos3svARB __indirect_glWindowPos3svARB

/*
 * Extensions
 */

#define glBlendColorEXT __indirect_glBlendColorEXT

#define glPolygonOffsetEXT __indirect_glPolygonOffsetEXT

#define glCopyTexSubImage3DEXT __indirect_glCopyTexSubImage3DEXT
#define glTexImage3DEXT __indirect_glTexImage3DEXT
#define glTexSubImage3DEXT __indirect_glTexSubImage3DEXT

#define glGetTexFilterFuncSGIS __indirect_glGetTexFilterFuncSGIS
#define glTexFilterFuncSGIS __indirect_glTexFilterFuncSGIS

#define glTexSubImage1DEXT __indirect_glTexSubImage1DEXT
#define glTexSubImage2DEXT __indirect_glTexSubImage2DEXT

#define glCopyTexImage1DEXT __indirect_glCopyTexImage1DEXT
#define glCopyTexImage2DEXT __indirect_glCopyTexImage2DEXT
#define glCopyTexSubImage1DEXT __indirect_glCopyTexSubImage1DEXT
#define glCopyTexSubImage2DEXT __indirect_glCopyTexSubImage2DEXT

#define glGetHistogramEXT __indirect_glGetHistogramEXT
#define glGetHistogramParameterfvEXT __indirect_glGetHistogramParameterfvEXT
#define glGetHistogramParameterivEXT __indirect_glGetHistogramParameterivEXT
#define glGetMinmaxEXT __indirect_glGetMinmaxEXT
#define glGetMinmaxParameterfvEXT __indirect_glGetMinmaxParameterfvEXT
#define glGetMinmaxParameterivEXT __indirect_glGetMinmaxParameterivEXT
#define glHistogramEXT __indirect_glHistogramEXT
#define glMinmaxEXT __indirect_glMinmaxEXT
#define glResetHistogramEXT __indirect_glResetHistogramEXT
#define glResetMinmaxEXT __indirect_glResetMinmaxEXT

#define glConvolutionFilter1DEXT __indirect_glConvolutionFilter1DEXT
#define glConvolutionFilter2DEXT __indirect_glConvolutionFilter2DEXT
#define glConvolutionParameterfEXT __indirect_glConvolutionParameterfEXT
#define glConvolutionParameterfvEXT __indirect_glConvolutionParameterfvEXT
#define glConvolutionParameteriEXT __indirect_glConvolutionParameteriEXT
#define glConvolutionParameterivEXT __indirect_glConvolutionParameterivEXT
#define glCopyConvolutionFilter1DEXT __indirect_glCopyConvolutionFilter1DEXT
#define glCopyConvolutionFilter2DEXT __indirect_glCopyConvolutionFilter2DEXT
#define glGetConvolutionFilterEXT __indirect_glGetConvolutionFilterEXT
#define glGetConvolutionParameterfvEXT __indirect_glGetConvolutionParameterfvEXT
#define glGetConvolutionParameterivEXT __indirect_glGetConvolutionParameterivEXT
#define glGetSeparableFilterEXT __indirect_glGetSeparableFilterEXT
#define glSeparableFilter2DEXT __indirect_glSeparableFilter2DEXT

#define glColorTableSGI __indirect_glColorTableSGI
#define glColorTableParameterfvSGI __indirect_glColorTableParameterfvSGI
#define glColorTableParameterivSGI __indirect_glColorTableParameterivSGI
#define glCopyColorTableSGI __indirect_glCopyColorTableSGI
#define glGetColorTableSGI __indirect_glGetColorTableSGI
#define glGetColorTableParameterfvSGI __indirect_glGetColorTableParameterfvSGI
#define glGetColorTableParameterivSGI __indirect_glGetColorTableParameterivSGI

#define glPixelTexGenParameterfSGIS __indirect_glPixelTexGenParameterfSGIS
#define glPixelTexGenParameteriSGIS __indirect_glPixelTexGenParameteriSGIS
#define glGetPixelTexGenParameterfvSGIS __indirect_glGetPixelTexGenParameterfvSGIS
#define glGetPixelTexGenParameterivSGIS __indirect_glGetPixelTexGenParameterivSGIS

#define glTexImage4DSGIS __indirect_glTexImage4DSGIS
#define glTexSubImage4DSGIS __indirect_glTexSubImage4DSGIS

#define glAreTexturesResidentEXT __indirect_glAreTexturesResidentEXT
#define glBindTextureEXT __indirect_glBindTextureEXT
#define glDeleteTexturesEXT __indirect_glDeleteTexturesEXT
#define glGenTexturesEXT __indirect_glGenTexturesEXT
#define glIsTextureEXT __indirect_glIsTextureEXT
#define glPrioritizeTexturesEXT __indirect_glPrioritizeTexturesEXT

#define glDetailTexFuncSGIS __indirect_glDetailTexFuncSGIS
#define glGetDetailTexFuncSGIS __indirect_glGetDetailTexFuncSGIS

#define glGetSharpenTexFuncSGIS __indirect_glGetSharpenTexFuncSGIS
#define glSharpenTexFuncSGIS __indirect_glSharpenTexFuncSGIS

#define glSampleMaskSGIS __indirect_glSampleMaskSGIS
#define glSamplePatternSGIS __indirect_glSamplePatternSGIS

#define glArrayElementEXT __indirect_glArrayElementEXT
#define glColorPointerEXT __indirect_glColorPointerEXT
#define glDrawArraysEXT __indirect_glDrawArraysEXT
#define glEdgeFlagPointerEXT __indirect_glEdgeFlagPointerEXT
#define glGetPointervEXT __indirect_glGetPointervEXT
#define glIndexPointerEXT __indirect_glIndexPointerEXT
#define glNormalPointerEXT __indirect_glNormalPointerEXT
#define glTexCoordPointerEXT __indirect_glTexCoordPointerEXT
#define glVertexPointerEXT __indirect_glVertexPointerEXT

#define glBlendEquationEXT __indirect_glBlendEquationEXT

#define glSpriteParameterfSGIX __indirect_glSpriteParameterfSGIX
#define glSpriteParameterfvSGIX __indirect_glSpriteParameterfvSGIX
#define glSpriteParameteriSGIX __indirect_glSpriteParameteriSGIX
#define glSpriteParameterivSGIX __indirect_glSpriteParameterivSGIX

#define glPointParameterfEXT __indirect_glPointParameterfEXT
#define glPointParameterfvEXT __indirect_glPointParameterfvEXT

#define glGetInstrumentsSGIX __indirect_glGetInstrumentsSGIX
#define glInstrumentsBufferSGIX __indirect_glInstrumentsBufferSGIX
#define glPollInstrumentsSGIX __indirect_glPollInstrumentsSGIX
#define glReadInstrumentsSGIX __indirect_glReadInstrumentsSGIX
#define glStartInstrumentsSGIX __indirect_glStartInstrumentsSGIX
#define glStopInstrumentsSGIX __indirect_glStopInstrumentsSGIX

#define glFrameZoomSGIX __indirect_glFrameZoomSGIX

#define glReferencePlaneSGIX __indirect_glReferencePlaneSGIX

#define glFlushRasterSGIX __indirect_glFlushRasterSGIX

#define glGetImageTransformParameterfvHP __indirect_glGetImageTransformParameterfvHP
#define glGetImageTransformParameterivHP __indirect_glGetImageTransformParameterivHP
#define glImageTransformParameterfHP __indirect_glImageTransformParameterfHP
#define glImageTransformParameterfvHP __indirect_glImageTransformParameterfvHP
#define glImageTransformParameteriHP __indirect_glImageTransformParameteriHP
#define glImageTransformParameterivHP __indirect_glImageTransformParameterivHP

#define glColorSubTableEXT __indirect_glColorSubTableEXT
#define glCopyColorSubTableEXT __indirect_glCopyColorSubTableEXT

#define glHintPGI __indirect_glHintPGI

#define glColorTableEXT __indirect_glColorTableEXT
#define glGetColorTableEXT __indirect_glGetColorTableEXT
#define glGetColorTableParameterfvEXT __indirect_glGetColorTableParameterfvEXT
#define glGetColorTableParameterivEXT __indirect_glGetColorTableParameterivEXT

#define glGetListParameterfvSGIX __indirect_glGetListParameterfvSGIX
#define glGetListParameterivSGIX __indirect_glGetListParameterivSGIX
#define glListParameterfSGIX __indirect_glListParameterfSGIX
#define glListParameterfvSGIX __indirect_glListParameterfvSGIX
#define glListParameteriSGIX __indirect_glListParameteriSGIX
#define glListParameterivSGIX __indirect_glListParameterivSGIX

#define glIndexMaterialEXT __indirect_glIndexMaterialEXT

#define glIndexFuncEXT __indirect_glIndexFuncEXT

#define glLockArraysEXT __indirect_glLockArraysEXT
#define glUnlockArraysEXT __indirect_glUnlockArraysEXT

#define glCullParameterfvEXT __indirect_glCullParameterfvEXT
#define glCullParameterdvEXT __indirect_glCullParameterdvEXT

#define glBlendFuncSeparateINGR __indirect_glBlendFuncSeparateINGR

#define glWindowPos2iMESA __indirect_WindowPos2iMESA
#define glWindowPos2sMESA __indirect_WindowPos2sMESA
#define glWindowPos2fMESA __indirect_WindowPos2fMESA
#define glWindowPos2dMESA __indirect_WindowPos2dMESA
#define glWindowPos2ivMESA __indirect_WindowPos2ivMESA
#define glWindowPos2svMESA __indirect_WindowPos2svMESA
#define glWindowPos2fvMESA __indirect_WindowPos2fvMESA
#define glWindowPos2dvMESA __indirect_WindowPos2dvMESA
#define glWindowPos3iMESA __indirect_WindowPos3iMESA
#define glWindowPos3sMESA __indirect_WindowPos3sMESA
#define glWindowPos3fMESA __indirect_WindowPos3fMESA
#define glWindowPos3dMESA __indirect_WindowPos3dMESA
#define glWindowPos3ivMESA __indirect_WindowPos3ivMESA
#define glWindowPos3svMESA __indirect_WindowPos3svMESA
#define glWindowPos3fvMESA __indirect_WindowPos3fvMESA
#define glWindowPos3dvMESA __indirect_WindowPos3dvMESA
#define glWindowPos4iMESA __indirect_WindowPos4iMESA
#define glWindowPos4sMESA __indirect_WindowPos4sMESA
#define glWindowPos4fMESA __indirect_WindowPos4fMESA
#define glWindowPos4dMESA __indirect_WindowPos4dMESA
#define glWindowPos4ivMESA __indirect_WindowPos4ivMESA
#define glWindowPos4svMESA __indirect_WindowPos4svMESA
#define glWindowPos4fvMESA __indirect_WindowPos4fvMESA
#define glWindowPos4dvMESA __indirect_WindowPos4dvMESA

#define glResizeBuffersMESA __indirect_glResizeBuffersMESA

#define glActiveStencilFaceEXT __indirect_glActiveStencilFaceEXT

#define glPointParameterfARB __indirect_glPointParameterfARB
#define glPointParameterfvARB __indirect_glPointParameterfvARB

#define glActiveStencilFaceEXT __indirect_glActiveStencilFaceEXT

#define glWindowPos2dARB __indirect_glWindowPos2dARB
#define glWindowPos2iARB __indirect_glWindowPos2iARB
#define glWindowPos2fARB __indirect_glWindowPos2fARB
#define glWindowPos2iARB __indirect_glWindowPos2iARB
#define glWindowPos2sARB __indirect_glWindowPos2sARB
#define glWindowPos2dvARB __indirect_glWindowPos2dvARB
#define glWindowPos2fvARB __indirect_glWindowPos2fvARB
#define glWindowPos2ivARB __indirect_glWindowPos2ivARB
#define glWindowPos2svARB __indirect_glWindowPos2svARB
#define glWindowPos3dARB __indirect_glWindowPos3dARB
#define glWindowPos3fARB __indirect_glWindowPos3fARB
#define glWindowPos3iARB __indirect_glWindowPos3iARB
#define glWindowPos3sARB __indirect_glWindowPos3sARB
#define glWindowPos3dvARB __indirect_glWindowPos3dvARB
#define glWindowPos3fvARB __indirect_glWindowPos3fvARB
#define glWindowPos3ivARB __indirect_glWindowPos3ivARB
#define glWindowPos3svARB __indirect_glWindowPos3svARB

/* 145. GL_EXT_secondary_color / GL 1.4 */

#define glSecondaryColor3b __indirect_glSecondaryColor3b
#define glSecondaryColor3bv __indirect_glSecondaryColor3bv
#define glSecondaryColor3d __indirect_glSecondaryColor3d
#define glSecondaryColor3dv __indirect_glSecondaryColor3dv
#define glSecondaryColor3f __indirect_glSecondaryColor3f
#define glSecondaryColor3fv __indirect_glSecondaryColor3fv
#define glSecondaryColor3i __indirect_glSecondaryColor3i
#define glSecondaryColor3iv __indirect_glSecondaryColor3iv
#define glSecondaryColor3s __indirect_glSecondaryColor3s
#define glSecondaryColor3sv __indirect_glSecondaryColor3sv
#define glSecondaryColor3ub __indirect_glSecondaryColor3ub
#define glSecondaryColor3ubv __indirect_glSecondaryColor3ubv
#define glSecondaryColor3ui __indirect_glSecondaryColor3ui
#define glSecondaryColor3uiv __indirect_glSecondaryColor3uiv
#define glSecondaryColor3us __indirect_glSecondaryColor3us
#define glSecondaryColor3usv __indirect_glSecondaryColor3usv
#define glSecondaryColorPointer __indirect_glSecondaryColorPointer

/* 149. GL_EXT_fog_coord / GL 1.4 */

#define glFogCoordf __indirect_glFogCoordf
#define glFogCoordd __indirect_glFogCoordd
#define glFogCoordfv __indirect_glFogCoordfv
#define glFogCoorddv __indirect_glFogCoorddv
#define glFogCoordPointer __indirect_glFogCoordPointer

#endif /* _INDIRECT_WRAP_H_ */
