Import('*')

env = env.Clone()

env.Prepend(LIBPATH = [graw.dir])
env.Prepend(LIBS = [graw.name])

progs = [
    'clear'
]

for prog in progs:
    env.Program(
        target = prog,
        source = prog + '.c',
    )

