TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = i965simple

C_SOURCES = \
	brw_blit.c \
	brw_flush.c \
	brw_screen.c \
	brw_surface.c \
	brw_cc.c \
	brw_clip.c \
	brw_clip_line.c \
	brw_clip_point.c \
	brw_clip_state.c \
	brw_clip_tri.c \
	brw_clip_util.c \
	brw_context.c \
	brw_curbe.c \
	brw_draw.c \
	brw_draw_upload.c \
	brw_eu.c \
	brw_eu_debug.c \
	brw_eu_emit.c \
	brw_eu_util.c \
	brw_gs.c \
	brw_gs_emit.c \
	brw_gs_state.c \
	brw_misc_state.c \
	brw_sf.c \
	brw_sf_emit.c \
	brw_sf_state.c \
	brw_state.c \
	brw_state_batch.c \
	brw_state_cache.c \
	brw_state_pool.c \
	brw_state_upload.c \
	brw_tex_layout.c \
	brw_urb.c \
	brw_util.c \
	brw_vs.c \
	brw_vs_emit.c \
	brw_vs_state.c \
	brw_wm.c \
	brw_wm_iz.c \
	brw_wm_decl.c \
	brw_wm_glsl.c \
	brw_wm_sampler_state.c \
	brw_wm_state.c \
	brw_wm_surface_state.c

include ../../Makefile.template

symlinks:
