Import('*')

env = env.Clone()

radeon_sources = env.ParseSourceList('Makefile.sources', 'C_SOURCES')

env.PkgUseModules('DRM')

radeonwinsys = env.ConvenienceLibrary(
    target ='radeonwinsys',
    source = radeon_sources,
)

Export('radeonwinsys')
