Import('*')

env = env.Clone()

radeon_sources = [
    'radeon_drm_bo.c',
    'radeon_drm_cs.c',
    'radeon_drm_common.c',
]

try:
    env.ParseConfig('pkg-config --cflags libdrm_radeon')
except:
    print 'warning: not building r300g'
    Return()

env.Append(CPPPATH = '#/src/gallium/drivers/r300')

radeonwinsys = env.ConvenienceLibrary(
    target ='radeonwinsys',
    source = radeon_sources,
)

Export('radeonwinsys')
