Import('*')

env = drienv.Clone()

drivers = [
    softpipe,
    i915simple,
    inteldrm
]

env.SharedLibrary(
    target ='i915_dri.so',
    source = COMMON_GALLIUM_SOURCES,
    LIBS = drivers + mesa + auxiliaries + env['LIBS'],
)
