Import('*')

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_intel')

drivers = [
    st_dri,
    inteldrm,
    softpipe,
    i915simple,
    trace,
]

env.SharedLibrary(
    target ='i915_dri.so',
    source = COMMON_GALLIUM_SOURCES,
    LIBS = drivers + mesa + auxiliaries + env['LIBS'],
)
