#######################################################################
# SConscript for haiku winsys


Import('*')

if env['platform'] in ('haiku'):

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/gallium/include',
        '#/src/gallium/auxiliary',
        '#/src/gallium/drivers',
        '#/src/gallium/state_trackers/hgl',
    ])

    ws_haiku = env.ConvenienceLibrary(
        target = 'ws_haiku',
        source = [
           'hgl_sw_winsys.c',
        ]
    )
    Export('ws_haiku')
