/* autogenerated by bdf2c!  do not edit */

/* "Copyright (c) 1984, 1987 Adobe Systems Incorporated. All Rights Reserved. Copyright (c) 1988, 1991 Digital Equipment Corporation. All Rights Reserved." */


#include "internal.h"
/*
typedef struct {
   int width, height;
   int xorig, yorig;
   int xmove;
   const unsigned char *bitmap;
} GLUTBitmapChar;

typedef struct {
   const char *name;
   int height;
   int num;
   const GLUTBitmapChar *const *table;
} GLUTBitmapFont;
*/


static const unsigned char ch32data[] = {
   0x0
};
static const GLUTBitmapChar ch32 = { 1, 1, 0, 0, 2, ch32data };

static const unsigned char ch33data[] = {
   0x80,0x0,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar ch33 = { 1, 7, -1, 0, 3, ch33data };

static const unsigned char ch34data[] = {
   0xa0,0xa0
};
static const GLUTBitmapChar ch34 = { 3, 2, 0, -5, 4, ch34data };

static const unsigned char ch35data[] = {
   0x50,0x50,0xf8,0x50,0xf8,0x50,0x50
};
static const GLUTBitmapChar ch35 = { 5, 7, 0, 0, 5, ch35data };

static const unsigned char ch36data[] = {
   0x20,0xe0,0x90,0x10,0x60,0x80,0x90,0x70,0x20
};
static const GLUTBitmapChar ch36 = { 4, 9, 0, 1, 5, ch36data };

static const unsigned char ch37data[] = {
   0x44,0x2a,0x2a,0x56,0xa8,0xa4,0x7e
};
static const GLUTBitmapChar ch37 = { 7, 7, 0, 0, 8, ch37data };

static const unsigned char ch38data[] = {
   0x76,0x8d,0x98,0x74,0x6e,0x50,0x30
};
static const GLUTBitmapChar ch38 = { 8, 7, 0, 0, 8, ch38data };

static const unsigned char ch39data[] = {
   0x40,0xc0
};
static const GLUTBitmapChar ch39 = { 2, 2, 0, -5, 3, ch39data };

static const unsigned char ch40data[] = {
   0x20,0x40,0x40,0x80,0x80,0x80,0x40,0x40,0x20
};
static const GLUTBitmapChar ch40 = { 3, 9, 0, 2, 4, ch40data };

static const unsigned char ch41data[] = {
   0x80,0x40,0x40,0x20,0x20,0x20,0x40,0x40,0x80
};
static const GLUTBitmapChar ch41 = { 3, 9, 0, 2, 4, ch41data };

static const unsigned char ch42data[] = {
   0xa0,0x40,0xa0
};
static const GLUTBitmapChar ch42 = { 3, 3, 0, -4, 5, ch42data };

static const unsigned char ch43data[] = {
   0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar ch43 = { 5, 5, 0, 0, 6, ch43data };

static const unsigned char ch44data[] = {
   0x80,0x80,0x80
};
static const GLUTBitmapChar ch44 = { 1, 3, -1, 2, 3, ch44data };

static const unsigned char ch45data[] = {
   0xf0
};
static const GLUTBitmapChar ch45 = { 4, 1, -1, -2, 7, ch45data };

static const unsigned char ch46data[] = {
   0x80
};
static const GLUTBitmapChar ch46 = { 1, 1, -1, 0, 3, ch46data };

static const unsigned char ch47data[] = {
   0x80,0x80,0x40,0x40,0x40,0x20,0x20
};
static const GLUTBitmapChar ch47 = { 3, 7, 0, 0, 3, ch47data };

static const unsigned char ch48data[] = {
   0x60,0x90,0x90,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar ch48 = { 4, 7, 0, 0, 5, ch48data };

static const unsigned char ch49data[] = {
   0xe0,0x40,0x40,0x40,0x40,0xc0,0x40
};
static const GLUTBitmapChar ch49 = { 3, 7, -1, 0, 5, ch49data };

static const unsigned char ch50data[] = {
   0xf0,0x40,0x20,0x20,0x10,0x90,0x60
};
static const GLUTBitmapChar ch50 = { 4, 7, 0, 0, 5, ch50data };

static const unsigned char ch51data[] = {
   0xe0,0x10,0x10,0x60,0x10,0x90,0x60
};
static const GLUTBitmapChar ch51 = { 4, 7, 0, 0, 5, ch51data };

static const unsigned char ch52data[] = {
   0x10,0x10,0xf8,0x90,0x50,0x30,0x10
};
static const GLUTBitmapChar ch52 = { 5, 7, 0, 0, 5, ch52data };

static const unsigned char ch53data[] = {
   0xe0,0x90,0x10,0x10,0xe0,0x40,0x70
};
static const GLUTBitmapChar ch53 = { 4, 7, 0, 0, 5, ch53data };

static const unsigned char ch54data[] = {
   0x60,0x90,0x90,0x90,0xe0,0x40,0x30
};
static const GLUTBitmapChar ch54 = { 4, 7, 0, 0, 5, ch54data };

static const unsigned char ch55data[] = {
   0x40,0x40,0x40,0x20,0x20,0x90,0xf0
};
static const GLUTBitmapChar ch55 = { 4, 7, 0, 0, 5, ch55data };

static const unsigned char ch56data[] = {
   0x60,0x90,0x90,0x60,0x90,0x90,0x60
};
static const GLUTBitmapChar ch56 = { 4, 7, 0, 0, 5, ch56data };

static const unsigned char ch57data[] = {
   0xc0,0x20,0x70,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar ch57 = { 4, 7, 0, 0, 5, ch57data };

static const unsigned char ch58data[] = {
   0x80,0x0,0x0,0x0,0x80
};
static const GLUTBitmapChar ch58 = { 1, 5, -1, 0, 3, ch58data };

static const unsigned char ch59data[] = {
   0x80,0x80,0x80,0x0,0x0,0x0,0x80
};
static const GLUTBitmapChar ch59 = { 1, 7, -1, 2, 3, ch59data };

static const unsigned char ch60data[] = {
   0x20,0x40,0x80,0x40,0x20
};
static const GLUTBitmapChar ch60 = { 3, 5, -1, 0, 5, ch60data };

static const unsigned char ch61data[] = {
   0xf8,0x0,0xf8
};
static const GLUTBitmapChar ch61 = { 5, 3, 0, -1, 6, ch61data };

static const unsigned char ch62data[] = {
   0x80,0x40,0x20,0x40,0x80
};
static const GLUTBitmapChar ch62 = { 3, 5, 0, 0, 5, ch62data };

static const unsigned char ch63data[] = {
   0x40,0x0,0x40,0x40,0x20,0xa0,0xe0
};
static const GLUTBitmapChar ch63 = { 3, 7, 0, 0, 4, ch63data };

static const unsigned char ch64data[] = {
   0x3e,0x40,0x92,0xad,0xa5,0xa5,0x9d,0x42,0x3c
};
static const GLUTBitmapChar ch64 = { 8, 9, 0, 2, 9, ch64data };

static const unsigned char ch65data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10
};
static const GLUTBitmapChar ch65 = { 7, 7, 0, 0, 8, ch65data };

static const unsigned char ch66data[] = {
   0xf0,0x48,0x48,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar ch66 = { 5, 7, 0, 0, 6, ch66data };

static const unsigned char ch67data[] = {
   0x78,0xc4,0x80,0x80,0x80,0xc4,0x7c
};
static const GLUTBitmapChar ch67 = { 6, 7, 0, 0, 7, ch67data };

static const unsigned char ch68data[] = {
   0xf8,0x4c,0x44,0x44,0x44,0x4c,0xf8
};
static const GLUTBitmapChar ch68 = { 6, 7, 0, 0, 7, ch68data };

static const unsigned char ch69data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8
};
static const GLUTBitmapChar ch69 = { 5, 7, 0, 0, 6, ch69data };

static const unsigned char ch70data[] = {
   0xe0,0x40,0x40,0x70,0x40,0x48,0xf8
};
static const GLUTBitmapChar ch70 = { 5, 7, 0, 0, 6, ch70data };

static const unsigned char ch71data[] = {
   0x78,0xc4,0x84,0x9c,0x80,0xc4,0x7c
};
static const GLUTBitmapChar ch71 = { 6, 7, 0, 0, 7, ch71data };

static const unsigned char ch72data[] = {
   0xee,0x44,0x44,0x7c,0x44,0x44,0xee
};
static const GLUTBitmapChar ch72 = { 7, 7, 0, 0, 8, ch72data };

static const unsigned char ch73data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0
};
static const GLUTBitmapChar ch73 = { 3, 7, 0, 0, 4, ch73data };

static const unsigned char ch74data[] = {
   0xc0,0xa0,0x20,0x20,0x20,0x20,0x70
};
static const GLUTBitmapChar ch74 = { 4, 7, 0, 0, 4, ch74data };

static const unsigned char ch75data[] = {
   0xec,0x48,0x50,0x60,0x50,0x48,0xec
};
static const GLUTBitmapChar ch75 = { 6, 7, 0, 0, 7, ch75data };

static const unsigned char ch76data[] = {
   0xf8,0x48,0x40,0x40,0x40,0x40,0xe0
};
static const GLUTBitmapChar ch76 = { 5, 7, 0, 0, 6, ch76data };

static const unsigned char ch77data[] = {
   0xeb,0x80,0x49,0x0,0x55,0x0,0x55,0x0,0x63,0x0,0x63,0x0,0xe3,0x80
};
static const GLUTBitmapChar ch77 = { 9, 7, 0, 0, 10, ch77data };

static const unsigned char ch78data[] = {
   0xe4,0x4c,0x4c,0x54,0x54,0x64,0xee
};
static const GLUTBitmapChar ch78 = { 7, 7, 0, 0, 8, ch78data };

static const unsigned char ch79data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78
};
static const GLUTBitmapChar ch79 = { 6, 7, 0, 0, 7, ch79data };

static const unsigned char ch80data[] = {
   0xe0,0x40,0x40,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar ch80 = { 5, 7, 0, 0, 6, ch80data };

static const unsigned char ch81data[] = {
   0xc,0x18,0x70,0xcc,0x84,0x84,0x84,0xcc,0x78
};
static const GLUTBitmapChar ch81 = { 6, 9, 0, 2, 7, ch81data };

static const unsigned char ch82data[] = {
   0xec,0x48,0x50,0x70,0x48,0x48,0xf0
};
static const GLUTBitmapChar ch82 = { 6, 7, 0, 0, 7, ch82data };

static const unsigned char ch83data[] = {
   0xe0,0x90,0x10,0x60,0xc0,0x90,0x70
};
static const GLUTBitmapChar ch83 = { 4, 7, 0, 0, 5, ch83data };

static const unsigned char ch84data[] = {
   0x70,0x20,0x20,0x20,0x20,0xa8,0xf8
};
static const GLUTBitmapChar ch84 = { 5, 7, 0, 0, 6, ch84data };

static const unsigned char ch85data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee
};
static const GLUTBitmapChar ch85 = { 7, 7, 0, 0, 8, ch85data };

static const unsigned char ch86data[] = {
   0x10,0x10,0x28,0x28,0x6c,0x44,0xee
};
static const GLUTBitmapChar ch86 = { 7, 7, 0, 0, 8, ch86data };

static const unsigned char ch87data[] = {
   0x22,0x0,0x22,0x0,0x55,0x0,0x55,0x0,0xc9,0x80,0x88,0x80,0xdd,0xc0
};
static const GLUTBitmapChar ch87 = { 10, 7, 0, 0, 10, ch87data };

static const unsigned char ch88data[] = {
   0xee,0x44,0x28,0x10,0x28,0x44,0xee
};
static const GLUTBitmapChar ch88 = { 7, 7, 0, 0, 8, ch88data };

static const unsigned char ch89data[] = {
   0x38,0x10,0x10,0x28,0x28,0x44,0xee
};
static const GLUTBitmapChar ch89 = { 7, 7, 0, 0, 8, ch89data };

static const unsigned char ch90data[] = {
   0xf8,0x88,0x40,0x20,0x10,0x88,0xf8
};
static const GLUTBitmapChar ch90 = { 5, 7, 0, 0, 6, ch90data };

static const unsigned char ch91data[] = {
   0xc0,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0xc0
};
static const GLUTBitmapChar ch91 = { 2, 9, 0, 2, 3, ch91data };

static const unsigned char ch92data[] = {
   0x20,0x20,0x40,0x40,0x40,0x80,0x80
};
static const GLUTBitmapChar ch92 = { 3, 7, 0, 0, 3, ch92data };

static const unsigned char ch93data[] = {
   0xc0,0x40,0x40,0x40,0x40,0x40,0x40,0x40,0xc0
};
static const GLUTBitmapChar ch93 = { 2, 9, 0, 2, 3, ch93data };

static const unsigned char ch94data[] = {
   0xa0,0xa0,0x40
};
static const GLUTBitmapChar ch94 = { 3, 3, -1, -4, 5, ch94data };

static const unsigned char ch95data[] = {
   0xf8
};
static const GLUTBitmapChar ch95 = { 5, 1, 0, 3, 5, ch95data };

static const unsigned char ch96data[] = {
   0xc0,0x80
};
static const GLUTBitmapChar ch96 = { 2, 2, 0, -5, 3, ch96data };

static const unsigned char ch97data[] = {
   0xe0,0xa0,0x60,0x20,0xc0
};
static const GLUTBitmapChar ch97 = { 3, 5, 0, 0, 4, ch97data };

static const unsigned char ch98data[] = {
   0xe0,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar ch98 = { 4, 7, 0, 0, 5, ch98data };

static const unsigned char ch99data[] = {
   0x60,0x80,0x80,0x80,0x60
};
static const GLUTBitmapChar ch99 = { 3, 5, 0, 0, 4, ch99data };

static const unsigned char ch100data[] = {
   0x68,0x90,0x90,0x90,0x70,0x10,0x30
};
static const GLUTBitmapChar ch100 = { 5, 7, 0, 0, 5, ch100data };

static const unsigned char ch101data[] = {
   0x60,0x80,0xc0,0xa0,0x60
};
static const GLUTBitmapChar ch101 = { 3, 5, 0, 0, 4, ch101data };

static const unsigned char ch102data[] = {
   0xe0,0x40,0x40,0x40,0xe0,0x40,0x30
};
static const GLUTBitmapChar ch102 = { 4, 7, 0, 0, 4, ch102data };

static const unsigned char ch103data[] = {
   0xe0,0x90,0x60,0x40,0xa0,0xa0,0x70
};
static const GLUTBitmapChar ch103 = { 4, 7, 0, 2, 5, ch103data };

static const unsigned char ch104data[] = {
   0xd8,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar ch104 = { 5, 7, 0, 0, 5, ch104data };

static const unsigned char ch105data[] = {
   0x40,0x40,0x40,0x40,0xc0,0x0,0x40
};
static const GLUTBitmapChar ch105 = { 2, 7, 0, 0, 3, ch105data };

static const unsigned char ch106data[] = {
   0x80,0x40,0x40,0x40,0x40,0x40,0xc0,0x0,0x40
};
static const GLUTBitmapChar ch106 = { 2, 9, 0, 2, 3, ch106data };

static const unsigned char ch107data[] = {
   0x98,0x90,0xe0,0xa0,0x90,0x80,0x80
};
static const GLUTBitmapChar ch107 = { 5, 7, 0, 0, 5, ch107data };

static const unsigned char ch108data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xc0
};
static const GLUTBitmapChar ch108 = { 3, 7, 0, 0, 4, ch108data };

static const unsigned char ch109data[] = {
   0xdb,0x92,0x92,0x92,0xec
};
static const GLUTBitmapChar ch109 = { 8, 5, 0, 0, 8, ch109data };

static const unsigned char ch110data[] = {
   0xd8,0x90,0x90,0x90,0xe0
};
static const GLUTBitmapChar ch110 = { 5, 5, 0, 0, 5, ch110data };

static const unsigned char ch111data[] = {
   0x60,0x90,0x90,0x90,0x60
};
static const GLUTBitmapChar ch111 = { 4, 5, 0, 0, 5, ch111data };

static const unsigned char ch112data[] = {
   0xc0,0x80,0xe0,0x90,0x90,0x90,0xe0
};
static const GLUTBitmapChar ch112 = { 4, 7, 0, 2, 5, ch112data };

static const unsigned char ch113data[] = {
   0x38,0x10,0x70,0x90,0x90,0x90,0x70
};
static const GLUTBitmapChar ch113 = { 5, 7, 0, 2, 5, ch113data };

static const unsigned char ch114data[] = {
   0xe0,0x40,0x40,0x60,0xa0
};
static const GLUTBitmapChar ch114 = { 3, 5, 0, 0, 4, ch114data };

static const unsigned char ch115data[] = {
   0xe0,0x20,0x60,0x80,0xe0
};
static const GLUTBitmapChar ch115 = { 3, 5, 0, 0, 4, ch115data };

static const unsigned char ch116data[] = {
   0x30,0x40,0x40,0x40,0xe0,0x40
};
static const GLUTBitmapChar ch116 = { 4, 6, 0, 0, 4, ch116data };

static const unsigned char ch117data[] = {
   0x68,0x90,0x90,0x90,0x90
};
static const GLUTBitmapChar ch117 = { 5, 5, 0, 0, 5, ch117data };

static const unsigned char ch118data[] = {
   0x20,0x60,0x50,0x90,0xd8
};
static const GLUTBitmapChar ch118 = { 5, 5, 0, 0, 5, ch118data };

static const unsigned char ch119data[] = {
   0x28,0x6c,0x54,0x92,0xdb
};
static const GLUTBitmapChar ch119 = { 8, 5, 0, 0, 8, ch119data };

static const unsigned char ch120data[] = {
   0xd8,0x50,0x20,0x50,0xd8
};
static const GLUTBitmapChar ch120 = { 5, 5, 0, 0, 6, ch120data };

static const unsigned char ch121data[] = {
   0x40,0x40,0x20,0x30,0x50,0x48,0xdc
};
static const GLUTBitmapChar ch121 = { 6, 7, 1, 2, 5, ch121data };

static const unsigned char ch122data[] = {
   0xf0,0x90,0x40,0x20,0xf0
};
static const GLUTBitmapChar ch122 = { 4, 5, 0, 0, 5, ch122data };

static const unsigned char ch123data[] = {
   0x20,0x40,0x40,0x40,0x80,0x40,0x40,0x40,0x20
};
static const GLUTBitmapChar ch123 = { 3, 9, 0, 2, 4, ch123data };

static const unsigned char ch124data[] = {
   0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80,0x80
};
static const GLUTBitmapChar ch124 = { 1, 9, 0, 2, 2, ch124data };

static const unsigned char ch125data[] = {
   0x80,0x40,0x40,0x40,0x20,0x40,0x40,0x40,0x80
};
static const GLUTBitmapChar ch125 = { 3, 9, 0, 2, 4, ch125data };

static const unsigned char ch126data[] = {
   0x98,0x64
};
static const GLUTBitmapChar ch126 = { 6, 2, 0, -2, 7, ch126data };

static const unsigned char ch160data[] = {
   0x0
};
static const GLUTBitmapChar ch160 = { 1, 1, 0, 0, 2, ch160data };

static const unsigned char ch161data[] = {
   0x80,0x80,0x80,0x80,0x80,0x0,0x80
};
static const GLUTBitmapChar ch161 = { 1, 7, -1, 2, 3, ch161data };

static const unsigned char ch162data[] = {
   0x80,0xe0,0x90,0x80,0x90,0x70,0x10
};
static const GLUTBitmapChar ch162 = { 4, 7, 0, 1, 5, ch162data };

static const unsigned char ch163data[] = {
   0xf0,0xc8,0x40,0xe0,0x40,0x50,0x30
};
static const GLUTBitmapChar ch163 = { 5, 7, 0, 0, 5, ch163data };

static const unsigned char ch164data[] = {
   0x88,0x70,0x50,0x50,0x70,0x88
};
static const GLUTBitmapChar ch164 = { 5, 6, 0, -1, 5, ch164data };

static const unsigned char ch165data[] = {
   0x70,0x20,0xf8,0x20,0xd8,0x50,0x88
};
static const GLUTBitmapChar ch165 = { 5, 7, 0, 0, 5, ch165data };

static const unsigned char ch166data[] = {
   0x80,0x80,0x80,0x0,0x80,0x80,0x80
};
static const GLUTBitmapChar ch166 = { 1, 7, 0, 0, 2, ch166data };

static const unsigned char ch167data[] = {
   0xe0,0x90,0x20,0x50,0x90,0xa0,0x40,0x90,0x70
};
static const GLUTBitmapChar ch167 = { 4, 9, 0, 1, 5, ch167data };

static const unsigned char ch168data[] = {
   0xa0
};
static const GLUTBitmapChar ch168 = { 3, 1, -1, -6, 5, ch168data };

static const unsigned char ch169data[] = {
   0x38,0x44,0x9a,0xa2,0x9a,0x44,0x38
};
static const GLUTBitmapChar ch169 = { 7, 7, -1, 0, 9, ch169data };

static const unsigned char ch170data[] = {
   0xe0,0x0,0xa0,0x20,0xc0
};
static const GLUTBitmapChar ch170 = { 3, 5, 0, -2, 4, ch170data };

static const unsigned char ch171data[] = {
   0x50,0xa0,0xa0,0x50
};
static const GLUTBitmapChar ch171 = { 4, 4, 0, -1, 5, ch171data };

static const unsigned char ch172data[] = {
   0x8,0x8,0xf8
};
static const GLUTBitmapChar ch172 = { 5, 3, -1, -1, 7, ch172data };

static const unsigned char ch173data[] = {
   0xe0
};
static const GLUTBitmapChar ch173 = { 3, 1, 0, -2, 4, ch173data };

static const unsigned char ch174data[] = {
   0x38,0x44,0xaa,0xb2,0xba,0x44,0x38
};
static const GLUTBitmapChar ch174 = { 7, 7, -1, 0, 9, ch174data };

static const unsigned char ch175data[] = {
   0xe0
};
static const GLUTBitmapChar ch175 = { 3, 1, 0, -6, 4, ch175data };

static const unsigned char ch176data[] = {
   0x60,0x90,0x90,0x60
};
static const GLUTBitmapChar ch176 = { 4, 4, 0, -3, 4, ch176data };

static const unsigned char ch177data[] = {
   0xf8,0x0,0x20,0x20,0xf8,0x20,0x20
};
static const GLUTBitmapChar ch177 = { 5, 7, 0, 0, 6, ch177data };

static const unsigned char ch178data[] = {
   0xe0,0x40,0xa0,0x60
};
static const GLUTBitmapChar ch178 = { 3, 4, 0, -3, 3, ch178data };

static const unsigned char ch179data[] = {
   0xc0,0x20,0x40,0xe0
};
static const GLUTBitmapChar ch179 = { 3, 4, 0, -3, 3, ch179data };

static const unsigned char ch180data[] = {
   0x80,0x40
};
static const GLUTBitmapChar ch180 = { 2, 2, 0, -5, 3, ch180data };

static const unsigned char ch181data[] = {
   0x80,0x80,0xe8,0x90,0x90,0x90,0x90
};
static const GLUTBitmapChar ch181 = { 5, 7, 0, 2, 5, ch181data };

static const unsigned char ch182data[] = {
   0x28,0x28,0x28,0x28,0x68,0xe8,0xe8,0xe8,0x7c
};
static const GLUTBitmapChar ch182 = { 6, 9, 0, 2, 6, ch182data };

static const unsigned char ch183data[] = {
   0x80
};
static const GLUTBitmapChar ch183 = { 1, 1, 0, -2, 2, ch183data };

static const unsigned char ch184data[] = {
   0xc0,0x20,0x40
};
static const GLUTBitmapChar ch184 = { 3, 3, 0, 3, 4, ch184data };

static const unsigned char ch185data[] = {
   0xe0,0x40,0xc0,0x40
};
static const GLUTBitmapChar ch185 = { 3, 4, 0, -3, 3, ch185data };

static const unsigned char ch186data[] = {
   0xe0,0x0,0x40,0xa0,0x40
};
static const GLUTBitmapChar ch186 = { 3, 5, 0, -2, 4, ch186data };

static const unsigned char ch187data[] = {
   0xa0,0x50,0x50,0xa0
};
static const GLUTBitmapChar ch187 = { 4, 4, 0, -1, 5, ch187data };

static const unsigned char ch188data[] = {
   0x44,0x3e,0x2c,0xf4,0x48,0xc8,0x44
};
static const GLUTBitmapChar ch188 = { 7, 7, 0, 0, 8, ch188data };

static const unsigned char ch189data[] = {
   0x4e,0x24,0x2a,0xf6,0x48,0xc8,0x44
};
static const GLUTBitmapChar ch189 = { 7, 7, 0, 0, 8, ch189data };

static const unsigned char ch190data[] = {
   0x44,0x3e,0x2c,0xd4,0x28,0x48,0xe4
};
static const GLUTBitmapChar ch190 = { 7, 7, 0, 0, 8, ch190data };

static const unsigned char ch191data[] = {
   0xe0,0xa0,0x80,0x40,0x40,0x0,0x40
};
static const GLUTBitmapChar ch191 = { 3, 7, 0, 2, 4, ch191data };

static const unsigned char ch192data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x10,0x20
};
static const GLUTBitmapChar ch192 = { 7, 10, 0, 0, 8, ch192data };

static const unsigned char ch193data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x10,0x8
};
static const GLUTBitmapChar ch193 = { 7, 10, 0, 0, 8, ch193data };

static const unsigned char ch194data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28,0x10
};
static const GLUTBitmapChar ch194 = { 7, 10, 0, 0, 8, ch194data };

static const unsigned char ch195data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28,0x14
};
static const GLUTBitmapChar ch195 = { 7, 10, 0, 0, 8, ch195data };

static const unsigned char ch196data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x0,0x28
};
static const GLUTBitmapChar ch196 = { 7, 9, 0, 0, 8, ch196data };

static const unsigned char ch197data[] = {
   0xee,0x44,0x7c,0x28,0x28,0x38,0x10,0x10,0x28,0x10
};
static const GLUTBitmapChar ch197 = { 7, 10, 0, 0, 8, ch197data };

static const unsigned char ch198data[] = {
   0xef,0x49,0x78,0x2e,0x28,0x39,0x1f
};
static const GLUTBitmapChar ch198 = { 8, 7, 0, 0, 9, ch198data };

static const unsigned char ch199data[] = {
   0x60,0x10,0x20,0x78,0xc4,0x80,0x80,0x80,0xc4,0x7c
};
static const GLUTBitmapChar ch199 = { 6, 10, 0, 3, 7, ch199data };

static const unsigned char ch200data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x20,0x40
};
static const GLUTBitmapChar ch200 = { 5, 10, 0, 0, 6, ch200data };

static const unsigned char ch201data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x20,0x10
};
static const GLUTBitmapChar ch201 = { 5, 10, 0, 0, 6, ch201data };

static const unsigned char ch202data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x50,0x20
};
static const GLUTBitmapChar ch202 = { 5, 10, 0, 0, 6, ch202data };

static const unsigned char ch203data[] = {
   0xf8,0x48,0x40,0x70,0x40,0x48,0xf8,0x0,0x50
};
static const GLUTBitmapChar ch203 = { 5, 9, 0, 0, 6, ch203data };

static const unsigned char ch204data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0x40,0x80
};
static const GLUTBitmapChar ch204 = { 3, 10, 0, 0, 4, ch204data };

static const unsigned char ch205data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0x40,0x20
};
static const GLUTBitmapChar ch205 = { 3, 10, 0, 0, 4, ch205data };

static const unsigned char ch206data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0xa0,0x40
};
static const GLUTBitmapChar ch206 = { 3, 10, 0, 0, 4, ch206data };

static const unsigned char ch207data[] = {
   0xe0,0x40,0x40,0x40,0x40,0x40,0xe0,0x0,0xa0
};
static const GLUTBitmapChar ch207 = { 3, 9, 0, 0, 4, ch207data };

static const unsigned char ch208data[] = {
   0xf8,0x4c,0x44,0xe4,0x44,0x4c,0xf8
};
static const GLUTBitmapChar ch208 = { 6, 7, 0, 0, 7, ch208data };

static const unsigned char ch209data[] = {
   0xe4,0x4c,0x4c,0x54,0x54,0x64,0xee,0x0,0x50,0x28
};
static const GLUTBitmapChar ch209 = { 7, 10, 0, 0, 8, ch209data };

static const unsigned char ch210data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x20,0x40
};
static const GLUTBitmapChar ch210 = { 6, 10, 0, 0, 7, ch210data };

static const unsigned char ch211data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x10,0x8
};
static const GLUTBitmapChar ch211 = { 6, 10, 0, 0, 7, ch211data };

static const unsigned char ch212data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50,0x20
};
static const GLUTBitmapChar ch212 = { 6, 10, 0, 0, 7, ch212data };

static const unsigned char ch213data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50,0x28
};
static const GLUTBitmapChar ch213 = { 6, 10, 0, 0, 7, ch213data };

static const unsigned char ch214data[] = {
   0x78,0xcc,0x84,0x84,0x84,0xcc,0x78,0x0,0x50
};
static const GLUTBitmapChar ch214 = { 6, 9, 0, 0, 7, ch214data };

static const unsigned char ch215data[] = {
   0x88,0x50,0x20,0x50,0x88
};
static const GLUTBitmapChar ch215 = { 5, 5, 0, 0, 6, ch215data };

static const unsigned char ch216data[] = {
   0x80,0x7c,0x66,0x52,0x52,0x4a,0x66,0x3e,0x1
};
static const GLUTBitmapChar ch216 = { 8, 9, 0, 1, 8, ch216data };

static const unsigned char ch217data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x10,0x20
};
static const GLUTBitmapChar ch217 = { 7, 10, 0, 0, 8, ch217data };

static const unsigned char ch218data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x10,0x8
};
static const GLUTBitmapChar ch218 = { 7, 10, 0, 0, 8, ch218data };

static const unsigned char ch219data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x28,0x10
};
static const GLUTBitmapChar ch219 = { 7, 10, 0, 0, 8, ch219data };

static const unsigned char ch220data[] = {
   0x38,0x6c,0x44,0x44,0x44,0x44,0xee,0x0,0x28
};
static const GLUTBitmapChar ch220 = { 7, 9, 0, 0, 8, ch220data };

static const unsigned char ch221data[] = {
   0x38,0x10,0x10,0x28,0x28,0x44,0xee,0x0,0x10,0x8
};
static const GLUTBitmapChar ch221 = { 7, 10, 0, 0, 8, ch221data };

static const unsigned char ch222data[] = {
   0xe0,0x40,0x70,0x48,0x70,0x40,0xe0
};
static const GLUTBitmapChar ch222 = { 5, 7, 0, 0, 6, ch222data };

static const unsigned char ch223data[] = {
   0xe0,0x50,0x50,0x60,0x50,0x50,0x20
};
static const GLUTBitmapChar ch223 = { 4, 7, 0, 0, 5, ch223data };

static const unsigned char ch224data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0x40,0x80
};
static const GLUTBitmapChar ch224 = { 3, 8, 0, 0, 4, ch224data };

static const unsigned char ch225data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0x40,0x20
};
static const GLUTBitmapChar ch225 = { 3, 8, 0, 0, 4, ch225data };

static const unsigned char ch226data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0,0x40
};
static const GLUTBitmapChar ch226 = { 3, 8, 0, 0, 4, ch226data };

static const unsigned char ch227data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0,0x50
};
static const GLUTBitmapChar ch227 = { 4, 8, 0, 0, 4, ch227data };

static const unsigned char ch228data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x0,0xa0
};
static const GLUTBitmapChar ch228 = { 3, 7, 0, 0, 4, ch228data };

static const unsigned char ch229data[] = {
   0xe0,0xa0,0x60,0x20,0xc0,0x40,0xa0,0x40
};
static const GLUTBitmapChar ch229 = { 3, 8, 0, 0, 4, ch229data };

static const unsigned char ch230data[] = {
   0xd8,0xa0,0x70,0x28,0xd8
};
static const GLUTBitmapChar ch230 = { 5, 5, 0, 0, 6, ch230data };

static const unsigned char ch231data[] = {
   0xc0,0x20,0x40,0x60,0x80,0x80,0x80,0x60
};
static const GLUTBitmapChar ch231 = { 3, 8, 0, 3, 4, ch231data };

static const unsigned char ch232data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0x40,0x80
};
static const GLUTBitmapChar ch232 = { 3, 8, 0, 0, 4, ch232data };

static const unsigned char ch233data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0x40,0x20
};
static const GLUTBitmapChar ch233 = { 3, 8, 0, 0, 4, ch233data };

static const unsigned char ch234data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0xa0,0x40
};
static const GLUTBitmapChar ch234 = { 3, 8, 0, 0, 4, ch234data };

static const unsigned char ch235data[] = {
   0x60,0x80,0xc0,0xa0,0x60,0x0,0xa0
};
static const GLUTBitmapChar ch235 = { 3, 7, 0, 0, 4, ch235data };

static const unsigned char ch236data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0x40,0x80
};
static const GLUTBitmapChar ch236 = { 3, 8, 0, 0, 4, ch236data };

static const unsigned char ch237data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0x40,0x20
};
static const GLUTBitmapChar ch237 = { 3, 8, 0, 0, 4, ch237data };

static const unsigned char ch238data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0xa0,0x40
};
static const GLUTBitmapChar ch238 = { 3, 8, 0, 0, 4, ch238data };

static const unsigned char ch239data[] = {
   0xe0,0x40,0x40,0x40,0xc0,0x0,0xa0
};
static const GLUTBitmapChar ch239 = { 3, 7, 0, 0, 4, ch239data };

static const unsigned char ch240data[] = {
   0x60,0x90,0x90,0x90,0x70,0xa0,0x70,0x40
};
static const GLUTBitmapChar ch240 = { 4, 8, 0, 0, 5, ch240data };

static const unsigned char ch241data[] = {
   0xd8,0x90,0x90,0x90,0xe0,0x0,0xa0,0x50
};
static const GLUTBitmapChar ch241 = { 5, 8, 0, 0, 5, ch241data };

static const unsigned char ch242data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0x20,0x40
};
static const GLUTBitmapChar ch242 = { 4, 8, 0, 0, 5, ch242data };

static const unsigned char ch243data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0x40,0x20
};
static const GLUTBitmapChar ch243 = { 4, 8, 0, 0, 5, ch243data };

static const unsigned char ch244data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0,0x40
};
static const GLUTBitmapChar ch244 = { 4, 8, 0, 0, 5, ch244data };

static const unsigned char ch245data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0,0x50
};
static const GLUTBitmapChar ch245 = { 4, 8, 0, 0, 5, ch245data };

static const unsigned char ch246data[] = {
   0x60,0x90,0x90,0x90,0x60,0x0,0xa0
};
static const GLUTBitmapChar ch246 = { 4, 7, 0, 0, 5, ch246data };

static const unsigned char ch247data[] = {
   0x20,0x0,0xf8,0x0,0x20
};
static const GLUTBitmapChar ch247 = { 5, 5, 0, 0, 6, ch247data };

static const unsigned char ch248data[] = {
   0x80,0x70,0x48,0x48,0x48,0x38,0x4
};
static const GLUTBitmapChar ch248 = { 6, 7, 1, 1, 5, ch248data };

static const unsigned char ch249data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x20,0x40
};
static const GLUTBitmapChar ch249 = { 5, 8, 0, 0, 5, ch249data };

static const unsigned char ch250data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x40,0x20
};
static const GLUTBitmapChar ch250 = { 5, 8, 0, 0, 5, ch250data };

static const unsigned char ch251data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x50,0x20
};
static const GLUTBitmapChar ch251 = { 5, 8, 0, 0, 5, ch251data };

static const unsigned char ch252data[] = {
   0x68,0x90,0x90,0x90,0x90,0x0,0x50
};
static const GLUTBitmapChar ch252 = { 5, 7, 0, 0, 5, ch252data };

static const unsigned char ch253data[] = {
   0x80,0xc0,0x40,0x60,0xa0,0x90,0xb8,0x0,0x20,0x10
};
static const GLUTBitmapChar ch253 = { 5, 10, 0, 2, 5, ch253data };

static const unsigned char ch254data[] = {
   0xc0,0x80,0xe0,0x90,0x90,0x90,0xe0,0x80,0x80
};
static const GLUTBitmapChar ch254 = { 4, 9, 0, 2, 5, ch254data };

static const unsigned char ch255data[] = {
   0x80,0xc0,0x40,0x60,0xa0,0x90,0xb8,0x0,0xa0
};
static const GLUTBitmapChar ch255 = { 5, 9, 0, 2, 5, ch255data };


static const GLUTBitmapChar *chars[] = {
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &ch32, &ch33, &ch34, &ch35, &ch36, &ch37, &ch38, &ch39, 
   &ch40, &ch41, &ch42, &ch43, &ch44, &ch45, &ch46, &ch47, 
   &ch48, &ch49, &ch50, &ch51, &ch52, &ch53, &ch54, &ch55, 
   &ch56, &ch57, &ch58, &ch59, &ch60, &ch61, &ch62, &ch63, 
   &ch64, &ch65, &ch66, &ch67, &ch68, &ch69, &ch70, &ch71, 
   &ch72, &ch73, &ch74, &ch75, &ch76, &ch77, &ch78, &ch79, 
   &ch80, &ch81, &ch82, &ch83, &ch84, &ch85, &ch86, &ch87, 
   &ch88, &ch89, &ch90, &ch91, &ch92, &ch93, &ch94, &ch95, 
   &ch96, &ch97, &ch98, &ch99, &ch100, &ch101, &ch102, &ch103, 
   &ch104, &ch105, &ch106, &ch107, &ch108, &ch109, &ch110, &ch111, 
   &ch112, &ch113, &ch114, &ch115, &ch116, &ch117, &ch118, &ch119, 
   &ch120, &ch121, &ch122, &ch123, &ch124, &ch125, &ch126, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   0, 0, 0, 0, 0, 0, 0, 0, 
   &ch160, &ch161, &ch162, &ch163, &ch164, &ch165, &ch166, &ch167, 
   &ch168, &ch169, &ch170, &ch171, &ch172, &ch173, &ch174, &ch175, 
   &ch176, &ch177, &ch178, &ch179, &ch180, &ch181, &ch182, &ch183, 
   &ch184, &ch185, &ch186, &ch187, &ch188, &ch189, &ch190, &ch191, 
   &ch192, &ch193, &ch194, &ch195, &ch196, &ch197, &ch198, &ch199, 
   &ch200, &ch201, &ch202, &ch203, &ch204, &ch205, &ch206, &ch207, 
   &ch208, &ch209, &ch210, &ch211, &ch212, &ch213, &ch214, &ch215, 
   &ch216, &ch217, &ch218, &ch219, &ch220, &ch221, &ch222, &ch223, 
   &ch224, &ch225, &ch226, &ch227, &ch228, &ch229, &ch230, &ch231, 
   &ch232, &ch233, &ch234, &ch235, &ch236, &ch237, &ch238, &ch239, 
   &ch240, &ch241, &ch242, &ch243, &ch244, &ch245, &ch246, &ch247, 
   &ch248, &ch249, &ch250, &ch251, &ch252, &ch253, &ch254, &ch255
};

const GLUTBitmapFont glutBitmapTimesRoman10 = {
   "-Adobe-Times-Medium-R-Normal--10-100-75-75-P-54-ISO8859-1",
   13, 256, chars
};
