C_SOURCES := \
	r600_blit.c \
	r600_buffer.c \
	r600_hw_context.c \
	radeonsi_pipe.c \
	r600_query.c \
	r600_resource.c \
	radeonsi_shader.c \
	r600_texture.c \
	r600_translate.c \
	radeonsi_pm4.c \
	radeonsi_compute.c \
	si_state.c \
	si_state_streamout.c \
	si_state_draw.c \
	si_commands.c
