import os

Import('*')

if env['platform'] in ['windows']:
     
    env = env.Clone()
     
    env.Append(CPPPATH = [
    	'#src/mesa',
    	'.',
    ])
     
    env.Append(CPPDEFINES = [
        '_GDI32_', # prevent wgl* being declared __declspec(dllimport)
        'BUILD_GL32', # declare gl* as __declspec(dllexport) in Mesa headers 
        'WIN32_THREADS', # use Win32 thread API
    ])
     
    sources = [
        'stw_context.c',
        'stw_device.c',
        'stw_ext_extensionsstring.c',
        'stw_ext_gallium.c',
        'stw_ext_pixelformat.c',
        'stw_ext_swapinterval.c',
        'stw_framebuffer.c',
        'stw_getprocaddress.c',
        'stw_pixelformat.c',
        'stw_tls.c',
        'stw_wgl.c',
    ]

    wgl = env.ConvenienceLibrary(
        target ='wgl',
        source = sources,
    )
    
    Export('wgl')
