TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = pipebuffer

C_SOURCES = \
	pb_buffer_fenced.c \
	pb_buffer_malloc.c \
	pb_bufmgr_alt.c \
	pb_bufmgr_cache.c \
	pb_bufmgr_debug.c \
	pb_bufmgr_fenced.c \
	pb_bufmgr_mm.c \
	pb_bufmgr_pool.c \
	pb_bufmgr_slab.c \
	pb_validate.c \
	pb_winsys.c

include ../../Makefile.template

symlinks:

