# Meta-driver which combines whichever software rasterizers have been
# built into a single convenience library.

TOP = ../../../..
include $(TOP)/configs/current

C_SOURCES = \
	sw.c

include ../../Makefile.template
