# src/mapi/glapi/Makefile.sources

GLAPI_SOURCES = \
	glapi_dispatch.c \
	glapi_entrypoint.c \
	glapi_gentable.c \
	glapi_getproc.c \
	glapi_nop.c \
	glapi.c \
	glapi.h \
	glapi_priv.h

X86_API =			\
	glapi_x86.S

X86_64_API =			\
	glapi_x86-64.S

SPARC_API =			\
	glapi_sparc.S
