Import('*')

env = env.Clone()

i915_sw_sources = env.ParseSourceList('Makefile.sources', 'C_SOURCES')

i915sw = env.ConvenienceLibrary(
    target ='i915sw',
    source = i915_sw_sources,
)

Export('i915sw')
