#######################################################################
# SConscript for xlib winsys


Import('*')

env = env.Clone()

env.Append(CPPPATH = [
    '#/src/gallium/include',
    '#/src/gallium/auxiliary',
    '#/src/gallium/drivers',
])

ws_drm = env.ConvenienceLibrary(
    target = 'ws_drm',
    source = [
       'sw_drm_api.c',
    ]
)
Export('ws_drm')
