#ifndef vl_defs_h
#define vl_defs_h

#define VL_BLOCK_WIDTH		8
#define VL_BLOCK_HEIGHT		8
#define VL_BLOCK_SIZE		(VL_BLOCK_WIDTH * VL_BLOCK_HEIGHT)
#define VL_MACROBLOCK_WIDTH	16
#define VL_MACROBLOCK_HEIGHT	16
#define VL_MACROBLOCK_SIZE	(VL_MACROBLOCK_WIDTH * VL_MACROBLOCK_HEIGHT)

#endif
