TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = llvmpipe

C_SOURCES = \
	lp_bld_arit.c \
	lp_bld_pack.c \
	lp_bld_unpack.c \
	lp_bld_load.c \
	lp_bld_store.c \
	lp_bld_loop.c \
	lp_bld_logicop.c \
	lp_bld_blend.c \
	lp_clear.c \
	lp_flush.c \
	lp_query.c \
	lp_context.c \
	lp_draw_arrays.c \
	lp_prim_setup.c \
	lp_prim_vbuf.c \
	lp_quad_pipe.c \
	lp_quad_stipple.c \
	lp_quad_depth_test.c \
	lp_quad_fs.c \
	lp_quad_blend.c \
	lp_screen.c \
        lp_setup.c \
	lp_state_blend.c \
	lp_state_clip.c \
	lp_state_derived.c \
	lp_state_fs.c \
	lp_state_sampler.c \
	lp_state_rasterizer.c \
	lp_state_surface.c \
	lp_state_vertex.c \
	lp_texture.c \
	lp_tex_sample.c \
	lp_tile_cache.c \
	lp_surface.c 

include ../../Makefile.template
