##############################################################################
# 
# Mesa-3.0 Makefile for DirectX 6 Driver                             
#
# By Leigh McRae
#
# http://www.altsoftware.com/
#
# Copyright (c) 1999-1998  alt.software inc.  All Rights Reserved     
##############################################################################
NAME=
TARGET= WGL Driver (D3DHAL)

D3D_DIR=$(MAKEDIR)\D3D
TARGET_DIR=e:\WinNT\System32
TEMP_DIR=c:\Temp

SPACE=-
LINKER=link.exe

INCLUDE=$(SDKROOT)\include;$(INCLUDE)
LIB=$(SDKROOT)\lib;$(LIB)
##############################################################################
CFLAGS  = /c /nologo /W1 /G5 /I..\ /I..\..\Include \
		/D "_WIN32" /D "WIN32" /D "_WINDOWS" /D "__WIN32__" /D "__MSC__"  /D "MESAD3D"
CPPFLAGS= /c /nologo /W1 /G5 /I..\ /I..\..\Include \
		/D "_WIN32" /D "WIN32" /D "_WINDOWS" /D "__WIN32__" /D "__MSC__"  /D "MESAD3D"

!IF "$(DEBUG)" == "1"

CFLAGS   = /MTd /Od /Z7 /Yd /D "_DEBUG" /D "D3D_DEBUG" $(CFLAGS)
CPPFLAGS = /MTd /Od /Z7 /Yd /D "_DEBUG" /D "D3D_DEBUG" $(CPPFLAGS)
BUILD_TYPE=debug

!ELSE

CFLAGS   = /MT /Ox /D "NDEBUG" $(CFLAGS)
CPPFLAGS = /MT /Ox /D "NDEBUG" $(CPPFLAGS)
BUILD_TYPE=release

!ENDIF
##############################################################################
SRCS_WGL = wgl.c D3Dvbrender.c DDrawPROCS.c NULLProcs.c Debug.c
SRCS_HAL = D3DInit.cpp D3DRaster.cpp D3DTextureMgr.cpp D3DUtils.cpp D3DCaps.cpp
OBJS_WGL = $(SRCS_WGL:.c=.obj)
OBJS_HAL = $(SRCS_HAL:.cpp=.obj)

WINLIBS = kernel32.lib user32.lib gdi32.lib oldnames.lib 
DXLIBS = 
LIBS = $(WINLIBS) $(DXLIBS) 
###############################################################################
# Primary Targets                                                             #
###############################################################################

default: header WGL HAL footer

all: default 

WGL : $(OBJS_WGL) 
        
HAL : $(OBJS_HAL)

install : forceit
	@echo $(SPACE)
	@echo ========================================
	@echo Install files created.
	@echo ========================================

        
###############################################################################
# Secondary Targets                                                           #
###############################################################################

clean:
	@echo ========================================
	@echo Cleaning $(TARGET)
	@del *.obj 
	@del *.dep 
	@del *.exp 
	@del *.ncb
	@del *.plg
	@del *.lib
	@echo ========================================

header:
	@echo ============================================================
	@echo Building $(TARGET)  ($(BUILD_TYPE) version)
	@echo ============================================================
	@echo $(SPACE)

footer:
	@echo $(SPACE)
	@echo ============================================================
	@echo DONE building $(TARGET)  ($(BUILD_TYPE) version)
	@echo ============================================================

forceit:




