TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = translate

C_SOURCES = \
	translate_generic.c \
	translate_sse.c \
	translate.c \
        translate_cache.c

include ../../Makefile.template

symlinks:

