Import('*')

translate = env.ConvenienceLibrary(
	target = 'translate',
	source = [
		'translate_generic.c',
		'translate_sse.c',
		'translate.c',
		'translate_cache.c',
	])

auxiliaries.insert(0, translate)
