Import('*')

progs = [
    'fp-tri',
    'tri-depth',
    'tri-depth2',
    'tri-depthwrite',
    'tri-depthwrite2',
    'tri-param',
    'tri-tex',
    'point-position',
]

for prog in progs:
    progs_env.Program(
        target = prog,
        source = [prog + '.c'],
    )
