Import('env')

if not env['GLUT']:
    Return()

env = env.Clone()

env.Prepend(CPPPATH = [
	'../util',
])

env.Prepend(LIBS = ['$GLUT_LIB'])

progs = [
    'fp-tri',
    'tri-depth',
    'tri-depth2',
    'tri-depthwrite',
    'tri-depthwrite2',
    'tri-inv',
    'tri-param',
    'tri-tex',
    'point-position',
]

for prog in progs:
    env.Program(
        target = prog,
        source = [prog + '.c'],
    )
