#######################################################################
# SConscript for egl-apis target

Import('*')

if env['platform'] == 'windows':

    env = env.Clone()

    env.Append(CPPPATH = [
            '#/src/gallium/state_trackers/vega',
    ])

    env.Append(LIBS = [
        'gdi32',
        'user32',
        'kernel32',
        'ws2_32',
    ])

    env['no_import_lib'] = 1

    api_libs = {
        'OpenVG': vgapi + st_vega,
    }

    for name in api_libs.keys():
        api = env.SharedLibrary(
            target = 'api_' + name,
            source = ['api_' + name + '.c'],
            LIBS = api_libs[name] + gallium + env['LIBS'],
        )
        env.InstallSharedLibrary(api)
