TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv40

C_SOURCES = \
	nv40_clear.c \
	nv40_context.c \
	nv40_draw.c \
	nv40_fragprog.c \
	nv40_fragtex.c \
	nv40_miptree.c \
	nv40_query.c \
	nv40_screen.c \
	nv40_state.c \
	nv40_state_blend.c \
	nv40_state_emit.c \
	nv40_state_fb.c \
	nv40_state_rasterizer.c \
	nv40_state_scissor.c \
	nv40_state_stipple.c \
	nv40_state_viewport.c \
	nv40_state_zsa.c \
	nv40_surface.c \
	nv40_transfer.c \
	nv40_vbo.c \
	nv40_vertprog.c

include ../../Makefile.template
