TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv40

C_SOURCES = \
	nv40_context.c \
	nv40_fragtex.c \
	nv40_screen.c \
	nv40_state.c

LIBRARY_INCLUDES = -I$(TOP)/src/gallium/drivers/nvfx

include ../../Makefile.template
