#######################################################################
# SConscript for xlib state_tracker

Import('*')

if env['platform'] == 'linux' \
        and 'mesa' in env['statetrackers'] \
        and ('softpipe' or 'i915simple' or 'trace') in env['drivers']:

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/mesa',
        '#/src/mesa/main',
    ])

    env.Append(CPPDEFINES = ['USE_XSHM'])

    st_xlib = env.ConvenienceLibrary(
	target = 'st_xlib',
	source = [ 'glxapi.c',
		'fakeglx.c',
		'fakeglx_fonts.c',
		'xm_api.c',
		]
    )
    Export('st_xlib')
