TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nvfx

C_SOURCES = \
	nvfx_clear.c \
	nvfx_state_emit.c \
	nvfx_state_blend.c \
	nvfx_state_rasterizer.c \
	nvfx_state_scissor.c \
	nvfx_transfer.c

include ../../Makefile.template
