Import('*')

env = env.Clone()

env.PrependUnique(delete_existing=1, CPPPATH = [
    '#/src/gallium/drivers',
])

nvfx = env.ConvenienceLibrary(
    target = 'nvfx',
    source = env.ParserSourceList('Makefile.sources', 'C_SOURCES')
    )

Export('nvfx')
