
# Mesa 3-D graphics library
# Version:  3.5
# Copyright (C) 1995-2001  Brian Paul

# Makefile for GLUT-based demo programs for Windows

!include <win32.mak>

##### MACROS #####

TOP    = ..
INCDIR = ..\include
LIBDIR = ..\lib

SRCS = cva.c \
	dinoshade.c \
	fogcoord.c \
	manytex.c \
	multipal.c \
	projtex.c \
	seccolor.c \
#	sharedtex.c \
	texline.c \
	texwrap.c \
	vptest1.c \
	vptest2.c \
	vptest3.c \
	vptorus.c \
	vpwarpmesh.c
	
!include "../mesawin32.mak"

##### TARGETS #####

clean::

clobber::
	@del readtex.c readtex.h

$(EXES) :$*.obj
	@echo $@
	$(link) -out:$@ $* /LIBPATH:$(LIBDIR) $(LIBS)
