
# Simple makefile for compiling test programs on Linux
# These programs aren't intended to be included with the normal
# distro.  They're not too interesting but they're good for testing.

TOP = ../..
LIBDIR = $(TOP)/lib

LIBS = -L$(LIBDIR) $(APP_LIB_DEPS)

SOURCES = antialias.c \
	bufferobj.c \
	cva.c \
	dinoshade.c \
	fogcoord.c \
	fptest1.c \
	fptexture.c \
	getprocaddress.c \
	manytex.c \
	multipal.c \
	projtex.c \
	seccolor.c \
	sharedtex.c \
	stencilwrap.c \
	texline.c \
	texrect.c \
	texwrap.c \
	vptest1.c \
	vptest2.c \
	vptest3.c \
	vptorus.c \
	vpwarpmesh.c \
	yuvrect.c \
	yuvsquare.c

OBJECTS = $(SOURCES:.c=.o)

PROGS = $(SOURCES:%.c=%)

INCLUDES = \
	-I. \
	-I$(TOP)/include

##### RULES #####

.SUFFIXES:
.SUFFIXES: .c

.c:
	$(CC) $(INCLUDES) $(CFLAGS) $< $(LIBS) -o $@

.c.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(DEFINES) $< -o $@

.S.o:
	$(CC) -c $(INCLUDES) $(CFLAGS) $(DEFINES)  $< -o $@


##### TARGETS #####

targets:  $(PROGS)

clean:
	rm -f $(PROGS)
	rm -f *.o

# auto code generation
getprocaddress: getprocaddress.c getproclist.h

getproclist.h: $(TOP)/src/mesa/glapi/APIspec getprocaddress.c getprocaddress.py
	python getprocaddress.py > getproclist.h


texrect: texrect.o readtex.o
	$(CC) texrect.o readtex.o $(LIBS) -o $@

texrect.o: texrect.c readtex.h
	$(CC) -c $(INCLUDES) $(CFLAGS) $(DEFINES) $< -o $@

readtex.o: readtex.c
	$(CC) -c $(INCLUDES) $(CFLAGS) $(DEFINES) $< -o $@


readtex.h: $(TOP)/progs/util/readtex.h
	ln -s $(TOP)/progs/util/readtex.h .

readtex.c: $(TOP)/progs/util/readtex.c
	ln -s $(TOP)/progs/util/readtex.c .

# Run 'make -f Makefile.X11 dep' to update the dependencies if you change
# what's included by any source file.
dep: $(SOURCES)
	makedepend -fdepend -Y $(INCLUDES) \
		$(SOURCES)


# Emacs tags
tags:
	etags `find . -name \*.[ch]` `find ../include`


include $(TOP)/Make-config

include depend
