TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv50

C_SOURCES = \
	nv50_clear.c \
	nv50_context.c \
	nv50_draw.c \
	nv50_miptree.c \
	nv50_query.c \
	nv50_program.c \
	nv50_screen.c \
	nv50_state.c \
	nv50_state_validate.c \
	nv50_surface.c \
	nv50_tex.c \
	nv50_transfer.c \
	nv50_vbo.c

include ../../Makefile.template
