#######################################################################
# SConscript for EGL


Import('*')

if env['platform'] != 'winddk':

	env = env.Clone()

	env.Append(CPPDEFINES = [
		'_EGL_DEFAULT_DISPLAY=\\"gdi\\"',
		'_EGL_DRIVER_SEARCH_DIR=\\"\\"',
		'_EGL_PLATFORM_WINDOWS',
		'KHRONOS_DLL_EXPORTS',
	])

	env.Append(CPPPATH = [
		'#/include',
	])

	egl_sources = [
		'eglapi.c',
		'eglconfig.c',
		'eglconfigutil.c',
		'eglcontext.c',
		'eglcurrent.c',
		'egldisplay.c',
		'egldriver.c',
		'eglglobals.c',
		'eglimage.c',
		'egllog.c',
		'eglmisc.c',
		'eglmode.c',
		'eglscreen.c',
		'eglstring.c',
		'eglsurface.c',
	]

	egl = env.SharedLibrary(
		target = 'libEGL',
		source = egl_sources,
	)

	env.InstallSharedLibrary(egl, version=(1, 4, 0))

	egl = [env.FindIxes(egl, 'LIBPREFIX', 'LIBSUFFIX')]

	Export('egl')
