Import('env')

if not env['GLUT']:
    Return()

env = env.Clone()

env.Prepend(LIBS = ['$GLUT_LIB'])

progs = [
      'drawoverhead',
      'teximage',
      'vbo',
      'vertexrate',
]

for prog in progs:
    env.Program(
        target = prog,
        source = [
            prog + '.c',
            'common.c',
            'glmain.c',
            ]
        )

