Import('*')

progs = [
      'copytex',
      'drawoverhead',
      'fbobind',
      'fill',
      'genmipmap',
      'readpixels',
      'swapbuffers',
      'teximage',
      'vbo',
      'vertexrate',
]

for prog in progs:
    progs_env.Program(
        target = prog,
        source = [
            prog + '.c',
            'common.c',
            'glmain.c',
            ]
        )

