#######################################################################
# SConscript for fbdev winsys


Import('*')

if env['platform'] == 'linux':

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/gallium/include',
        '#/src/gallium/auxiliary',
    ])

    ws_fbdev = env.ConvenienceLibrary(
        target = 'ws_fbdev',
        source = env.ParseSourceList('Makefile.sources', 'C_SOURCES'),
    )
    Export('ws_fbdev')
