#######################################################################
# SConscript for gdi winsys

Import('*')

if env['platform'] == 'windows':

	env = env.Clone()

	env.Append(CPPPATH = [
		'#src/mesa/glapi',
		'#src/mesa',
		'#src/mesa/main',
	])

	env.Append(CPPDEFINES = [
		'__GL_EXPORTS',
		'BUILD_GL32',
		'_GNU_H_WINDOWS32_DEFINES',
	])

	sources = [
		'opengl32.def',
		'wgl.c',
		'wmesa.c',
	]
		
	drivers = [
		softpipe,
	]

	env.Append(LIBS = ['gdi32', 'user32'])

	# TODO: write a wrapper function http://www.scons.org/wiki/WrapperFunctions
	env.SharedLibrary(
		target ='opengl32',
		source = sources,
		LIBS = glapi + mesa + drivers + auxiliaries + env['LIBS'],
	)
