#######################################################################
# SConscript for gdi winsys

Import('*')

if env['platform'] == 'windows':

	env = env.Clone()

	env.Append(CPPPATH = [
		'#src/gallium/state_trackers/wgl',
	])

	env.Append(CPPDEFINES = [
		'__GL_EXPORTS',
		'BUILD_GL32',
		'_GNU_H_WINDOWS32_DEFINES',
	])

	env.Append(LIBS = [
		'gdi32',
		'user32',
		'kernel32',
	])

	sources = [
		'#src/gallium/state_trackers/wgl/opengl32.def',
		'gdi_softpipe_winsys.c',
	]
		
	drivers = [
		softpipe,
	]

	env.SharedLibrary(
		target ='opengl32',
		source = sources,
		LIBS = wgl + glapi + mesa + drivers + auxiliaries + env['LIBS'],
	)
