#######################################################################
# SConscript for gdi winsys

Import('*')

if env['platform'] == 'windows':

	env = env.Clone()

	env.Append(CPPPATH = [
		'#src/mesa/state_tracker/wgl',
	])

	env.Append(CPPDEFINES = [
	])

	sources = [
		'#src/mesa/state_tracker/wgl/opengl32.def',
		'gdi_softpipe_winsys.c',
	]
		
	drivers = [
		softpipe,
	]

	env.Append(LIBS = [
		'gdi32', 
		'user32'
	])

	env.SharedLibrary(
		target ='opengl32',
		source = sources,
		LIBS = wgl + glapi + mesa + drivers + auxiliaries + env['LIBS'],
	)
