Import('*')

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_intel')

env.Append(CPPDEFINES = [
    'GALLIUM_SOFTPIPE',
    'GALLIUM_RBUG',
    'GALLIUM_TRACE'
])

env.Prepend(LIBS = [
    st_dri,
    i965drm,
    ws_wrapper,
    i965,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

module = env.LoadableModule(
    target = 'i965_dri.so',
    source = 'target.c',
    SHLIBPREFIX = '',
)

env.Alias('dri-i965', module)