Import('*')

if not 'i965' in env['drivers']:
    print 'warning: i965 pipe driver not built skipping i965_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_intel')

env.Append(CPPDEFINES = [
    'GALLIUM_SOFTPIPE',
    'GALLIUM_RBUG',
    'GALLIUM_TRACE'
])

env.Prepend(LIBS = [
    st_dri,
    i965drm,
    ws_wrapper,
    i965,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

env.LoadableModule(
    target = 'i965_dri.so',
    source = 'target.c',
    SHLIBPREFIX = '',
)
