Import('*')

if 'mesa' in env['statetrackers']:

	env = drienv.Clone()

	DRIVER_SOURCES = [
		'amd_buffer.c',
		'amd_context.c',
		'amd_screen.c',
		'amd_winsys_softpipe.c',
	]

	sources = \
		COMMON_GALLIUM_SOURCES + \
		DRIVER_SOURCES

	drivers = [
		softpipe,
		r300
	]

	# TODO: write a wrapper function http://www.scons.org/wiki/WrapperFunctions
	env.SharedLibrary(
		target ='amd_dri.so',
		source = sources,
		LIBS = drivers + mesa + auxiliaries + env['LIBS'],
	)

