mesa_dri_common_gallium_SOURCES := \
	utils.c \
	dri_util.c \
	xmlconfig.c

mesa_dri_common_SOURCES := \
	$(mesa_dri_common_gallium_SOURCES) \
        texmem.c \
        drirenderbuffer.c

# Paths are relative to MESA_TOP.
mesa_dri_common_INCLUDES := \
	include \
	src/egl/drivers/dri \
	src/egl/main \
	src/mapi \
	src/mesa \
	src/mesa/drivers/dri/common
