
# Makefile for sample programs for MS-DOS with DJGPP and ALLEGRO



INCDIR  =   ../include
LIBDIR  =   ../lib
include ../common.dja

 _PROGS = accum bitmap1 bitmap2 blendeq blendxor copy cursor depth    \
          eval fog font line logo nurb oglinfo olympic overlay point  \
          prim quad select shape sphere star stencil stretch texture  \
          tri wave

  PROGS = $(_PROGS:=.exe)


default: $(PROGS)

clean:
	del *. 

realclean: clean
	del *.exe

