Import('*')

progs = [
    'accum',
    'bitmap1',
    'bitmap2',
    'blendeq',
    'blendxor',
    'copy',
    'cursor',
    'depth',
    'eval',
    'fog',
    'font',
    'line',
    'logo',
    'nurb',
    #'oglinfo',
    'olympic',
    'overlay',
    'point',
    'prim',
    'quad',
    'rgbtoppm',
    'select',
    'shape',
    'sphere',
    'star',
    'stencil',
    'stretch',
    'texture',
    'tri',
    'wave',
]

for prog in progs:
    progs_env.Program(
        target = prog,
        source = prog + '.c',
    )
