Import('*')

if not env['GLUT']:
    Return()

env = env.Clone()

env.Prepend(CPPPATH = [
	'../util',
])

env.Prepend(LIBS = [
	util,
	'$GLUT_LIB'
])

if env['platform'] == 'windows':
    env.Append(CPPDEFINES = ['NOMINMAX'])
    env.Prepend(LIBS = ['winmm'])

progs = [
    'accum',
    'bitmap1',
    'bitmap2',
    'blendeq',
    'blendxor',
    'copy',
    'cursor',
    'depth',
    'eval',
    'fog',
    'font',
    'line',
    'logo',
    'nurb',
    #'oglinfo',
    'olympic',
    'overlay',
    'point',
    'prim',
    'quad',
    'rgbtoppm',
    'select',
    'shape',
    'sphere',
    'star',
    'stencil',
    'stretch',
    'texture',
    'tri',
    'wave',
]

for prog in progs:
    env.Program(
        target = prog,
        source = prog + '.c',
    )
