Import('env')

# 
# Auxiliary modules
#

SConscript('auxiliary/SConscript')

#
# Drivers
#

SConscript([
    'drivers/failover/SConscript', 
    'drivers/galahad/SConscript',
    'drivers/identity/SConscript', 
    'drivers/llvmpipe/SConscript', 
    'drivers/rbug/SConscript',
    'drivers/softpipe/SConscript',
    'drivers/svga/SConscript', 
    'drivers/trace/SConscript', 
])

if not env['msvc']:
    # These drivers do not build on MSVC compilers
    SConscript([
        'drivers/i915/SConscript', 
        'drivers/i965/SConscript',
        'drivers/r300/SConscript',
    ])

if env['dri']:
    # These drivers depend on drm headers
    SConscript([
        # XXX: nouveau drivers have a tight dependency on libdrm, so to enable
        # we need some version logic before we enable them. Also, ATM there is
        # no nouveau target in scons
        #'drivers/nouveau/SConscript', 
        #'drivers/nv50/SConscript', 
        #'drivers/nvfx/SConscript',
        'drivers/r600/SConscript', 
    ])

#
# State trackers
#

# Needed by some state trackers
SConscript('winsys/sw/null/SConscript')

SConscript('state_trackers/python/SConscript')
if env['platform'] != 'embedded':
    SConscript('state_trackers/glx/xlib/SConscript')
    SConscript('state_trackers/dri/SConscript')
    SConscript('state_trackers/xorg/SConscript')
    SConscript('state_trackers/egl/SConscript')
    SConscript('state_trackers/vega/SConscript')

if env['platform'] == 'windows':
    SConscript('state_trackers/wgl/SConscript')

#
# Winsys
# 

SConscript('winsys/SConscript')

#
# Targets
#

SConscript([
    'targets/graw-null/SConscript',
])

if env['x11']:
    SConscript([
        'targets/graw-xlib/SConscript',
        'targets/libgl-xlib/SConscript',
    ])

if env['platform'] == 'windows':
    SConscript([
        'targets/graw-gdi/SConscript',
        'targets/libgl-gdi/SConscript',
        #'egl-gdi/SConscript',
    ])

if env['dri']:
    SConscript([
        'targets/SConscript.dri',
        'targets/dri-i915/SConscript',
        'targets/dri-i965/SConscript',
        #'targets/dri-nouveau/SConscript',
        'targets/dri-r300/SConscript',
        'targets/dri-r600/SConscript',
        'targets/dri-swrast/SConscript',
        'targets/dri-vmwgfx/SConscript',
    ])

if env['xorg']:
    SConscript([
        #'targets/xorg-i915/SConscript',
        #'targets/xorg-i965/SConscript',
        #'targets/xorg-nouveau/SConscript',
        #'targets/xorg-radeon/SConscript',
        'targets/xorg-vmwgfx/SConscript',
    ])


#
# Unit tests & tools
#

if env['platform'] != 'embedded':
    SConscript('tests/unit/SConscript')
    SConscript('tests/graw/SConscript')
