Import('*')

env = env.Clone()

auxiliaries = []

Export('auxiliaries')


SConscript([
	# NOTE: order matters!
	'auxiliary/util/SConscript',
	'auxiliary/tgsi/SConscript',
	'auxiliary/cso_cache/SConscript',
	'auxiliary/draw/SConscript',
	#'auxiliary/gallivm/SConscript',
	'auxiliary/pipebuffer/SConscript',

	'drivers/softpipe/SConscript',
	'drivers/i915simple/SConscript',
	'drivers/i965simple/SConscript',
	'drivers/failover/SConscript',
	#'drivers/cell/SConscript',
])
