#######################################################################
# SConscript for dri state_tracker

Import('*')

if env['dri']:

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/mesa',
	'#/src/gallium/state_trackers/dri/common',
	'#/src/mesa/drivers/dri/common',
    ])

    env.Append(CPPDEFINES = [('__NOT_HAVE_DRM_H', '1')])

    st_drisw = env.ConvenienceLibrary(
	target = 'st_drisw',
	source = [ 'dri_context.c',
		'dri_drawable.c',
		'dri_screen.c',
		'dri1_helper.c',
		'drisw.c',
		]
    )
    Export('st_drisw')
