#######################################################################
# SConscript for xlib winsys


Import('*')

if env['platform'] in ('cygwin', 'darwin', 'freebsd', 'linux', 'sunos'):

    env = env.Clone()

    env.Append(CPPPATH = [
        '#/src/gallium/include',
        '#/src/gallium/auxiliary',
    ])

    ws_xlib = env.ConvenienceLibrary(
        target = 'ws_xlib',
        source = env.ParseSourceList('Makefile.sources', 'C_SOURCES'),
    )
    env.Alias('ws_xlib', ws_xlib)
    Export('ws_xlib')
