Import('*')

env = env.Clone()

if env['platform'] == 'windows':
    env.PrependUnique(LIBS = [
        'user32',
    ])

env.Prepend(LIBS = [glsl])

env.Program(
    target = 'purify',
    source = ['purify.c'],
)

env.Program(
    target = 'tokenise',
    source = ['tokenise.c'],
)

env.Program(
    target = 'version',
    source = ['version.c'],
)

env.Program(
    target = 'process',
    source = ['process.c'],
)
