TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = vl

C_SOURCES = \
	vl_bitstream_parser.c \
	vl_mpeg12_mc_renderer.c \
	vl_compositor.c \
        vl_csc.c \
	vl_shader_build.c

include ../../Makefile.template
