Import('*')

vl = env.ConvenienceLibrary(
	target = 'vl',
	source = [
		'vl_bitstream_parser.c',
		'vl_mpeg12_mc_renderer.c',
		'vl_compositor.c',
                'vl_csc.c',
	])

auxiliaries.insert(0, vl)
