Import('*')

env = env.Clone()

env.ParseConfig('pkg-config --cflags libdrm')

i965drm_sources = [
    'i965_drm_buffer.c',
    'i965_drm_winsys.c',
]

i965drm = env.ConvenienceLibrary(
    target ='i965drm',
    source = i965drm_sources,
)

Export('i965drm')
