TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = r300

C_SOURCES = \
	r300_blit.c \
	r300_clear.c \
	r300_context.c \
	r300_screen.c \
	r300_state.c \
	r300_surface.c

include ../../Makefile.template

symlinks:
