TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = r300

C_SOURCES = \
	r300_chipset.c \
	r300_clear.c \
	r300_context.c \
	r300_debug.c \
	r300_emit.c \
	r300_flush.c \
	r300_query.c \
	r300_render.c \
	r300_screen.c \
	r300_state.c \
	r300_state_derived.c \
	r300_state_invariant.c \
	r300_state_shader.c \
	r300_state_tcl.c \
	r300_surface.c \
	r300_texture.c

include ../../Makefile.template
