Import('*')

r300compiler = SConscript('#/src/mesa/drivers/dri/r300/compiler/SConscript')

env = env.Clone()
# add the paths for r300compiler
env.Append(CPPPATH = [
    '#/src/mesa/drivers/dri/r300/compiler', 
    '#/include', 
    '#/src/mesa',
])

r300 = env.ConvenienceLibrary(
    target = 'r300',
    source = [
        'r300_blit.c',
        'r300_chipset.c',
        'r300_context.c',
        'r300_debug.c',
        'r300_emit.c',
        'r300_flush.c',
        'r300_fs.c',
        'r300_hyperz.c',
        'r300_query.c',
        'r300_render.c',
        'r300_render_stencilref.c',
        'r300_render_translate.c',
        'r300_resource.c',
        'r300_screen.c',
        'r300_screen_buffer.c',
        'r300_state.c',
        'r300_state_derived.c',
        'r300_vs.c',
        'r300_vs_draw.c',
        'r300_texture.c',
        'r300_texture_desc.c',
        'r300_tgsi_to_rc.c',
        'r300_transfer.c',
    ] + r300compiler) + r300compiler

env.Alias('r300', r300)

Export('r300')

