Import('*')

env = env.Clone()

r300 = env.ConvenienceLibrary(
	target = 'r300',
	source = [
		'r300_blit.c',
		'r300_clear.c',
		'r300_context.c',
		'r300_screen.c',
		'r300_state.c',
		'r300_surface.c',
	])

Export('r300')

