TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv20

C_SOURCES = \
	nv20_clear.c \
	nv20_context.c \
	nv20_fragprog.c \
	nv20_fragtex.c \
	nv20_miptree.c \
	nv20_prim_vbuf.c \
	nv20_screen.c \
	nv20_state.c \
	nv20_state_emit.c \
	nv20_surface.c \
	nv20_transfer.c \
	nv20_vbo.c
#	nv20_vertprog.c

include ../../Makefile.template
