C_SOURCES := \
	fd2_blend.c \
	fd2_compiler.c \
	fd2_context.c \
	fd2_draw.c \
	fd2_emit.c \
	fd2_gmem.c \
	fd2_program.c \
	fd2_rasterizer.c \
	fd2_screen.c \
	fd2_texture.c \
	fd2_util.c \
	fd2_zsa.c \
	disasm-a2xx.c \
	ir-a2xx.c
