Import('*')

env = drienv.Clone()

inteldrm_sources = [
    'intel_drm_api.c',
    'intel_drm_batchbuffer.c',
    'intel_drm_buffer.c',
    'intel_drm_fence.c',
]

inteldrm = env.ConvenienceLibrary(
    target ='inteldrm',
    source = inteldrm_sources,
)

Export('inteldrm')
