TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = cso_cache

DRIVER_SOURCES = \
	cso_cache.c \
	cso_hash.c

C_SOURCES = \
	$(DRIVER_SOURCES)

ASM_SOURCES = 

include ../../Makefile.template

symlinks:

