Import('*')

progs = [
      'array',
      'bitmap',
      'brick',
      'bump',
      'convolutions',
      'deriv',
      'fragcoord',
      'identity',
      'linktest',
      'mandelbrot',
      'multinoise',
      'multitex',
      'noise',
      'noise2',
      'pointcoord',
      'points',
      'samplers',
      'shadow_sampler',
      'skinning',
      'texaaline',
      'texdemo1',
      'toyball',
      'trirast',
      'twoside',
      'vert-or-frag-only',
      'vert-tex',
]

for prog in progs:
    progs_env.Program(
        target = prog,
        source = prog + '.c',
    )
    
