Import('*')

if env['platform'] == 'windows':
    SConscript('getopt/SConscript')
    SConscript('talloc/SConscript')

SConscript('glsl/SConscript')
SConscript('mapi/glapi/SConscript')
SConscript('mesa/SConscript')

SConscript('mapi/vgapi/SConscript')

if env['platform'] != 'embedded':
    SConscript('egl/main/SConscript')
    SConscript('glut/glx/SConscript')

SConscript('gallium/SConscript')

