Import('*')

if not 'i915' in env['drivers']:
    print 'warning: i915 pipe driver not built skipping i915_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_intel')

env.Append(CPPDEFINES = ['GALLIUM_RBUG', 'GALLIUM_TRACE', 'GALLIUM_GALAHAD'])

env.Prepend(LIBS = [
    ws_wrapper,
    st_dri,
    i915drm,
    i915,
    galahad,
    trace,
    rbug,
    mesa,
    glsl,
    gallium,
    COMMON_DRI_DRM_OBJECTS
])

env.LoadableModule(
    target = 'i915_dri.so',
    source = 'target.c',
    SHLIBPREFIX = '',
)
