Import('*')

if not 'i915' in env['drivers']:
    print 'warning: i915 pipe driver not built skipping i915_dri.so'
    Return()

env = drienv.Clone()

env.ParseConfig('pkg-config --cflags --libs libdrm_intel')

env.Prepend(LIBS = [
    st_dri,
    i915drm,
    i915,
    trace,
    mesa,
    glsl,
    gallium
])

env.LoadableModule(
    target ='i915_dri.so',
    source = COMMON_GALLIUM_SOURCES,
    SHLIBPREFIX = '',
)
