TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = i915

# get C_SOURCES
include Makefile.sources

include ../../Makefile.template

# FIXME: Remove when this driver is converted to automake.
all: default
