#######################################################################
# SConscript for xlib winsys

Import('*')

env = env.Clone()

env.Append(CPPPATH = [
	'#/src/mesa',
	'#/src/mesa/main',
])

sources = [
	'glxapi.c',
	'fakeglx.c',
	'xfonts.c',
	'xm_api.c',
	'xm_winsys.c',
	'xm_winsys_aub.c',
	'brw_aub.c',
]
	
drivers = [
	softpipe,
]

# TODO: write a wrapper function http://www.scons.org/wiki/WrapperFunctions
env.SharedLibrary(
	target ='GL',
	source = sources,
	LIBS = glapi + mesa + drivers + auxiliaries + env['LIBS'],
)
