C_SOURCES := \
	freedreno_util.c \
	freedreno_fence.c \
	freedreno_resource.c \
	freedreno_surface.c \
	freedreno_draw.c \
	freedreno_state.c \
	freedreno_texture.c \
	freedreno_context.c \
	freedreno_screen.c \
	freedreno_gmem.c
