TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = util

C_SOURCES = \
	p_debug.c \
	u_blit.c \
	u_draw_quad.c \
	u_gen_mipmap.c \
	u_handle_table.c \
	u_hash_table.c \
	u_math.c \
	u_mm.c \
	u_rect.c \
	u_simple_shaders.c \
	u_snprintf.c \
	u_stream_stdc.c \
	u_stream_wd.c \
	u_tile.c \
	u_time.c \
	u_timed_winsys.c

include ../../Makefile.template

symlinks:

