TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = util

C_SOURCES = \
	p_debug.c \
	p_tile.c \
	p_util.c \
	u_blit.c \
	u_draw_quad.c \
	u_gen_mipmap.c \
	u_handle_table.c \
	u_hash_table.c \
	u_mm.c \
	u_simple_shaders.c \
	u_snprintf.c \
	u_time.c

include ../../Makefile.template

symlinks:

