Import('*')

util = env.ConvenienceLibrary(
	target = 'util',
	source = [
		'p_debug.c',
		'p_tile.c',
		'p_util.c',
		'u_draw_quad.c',
		'u_gen_mipmap.c',
		'u_handle_table.c',
		'u_hash_table.c',
		'u_mm.c',
		'u_snprintf.c',
	])

auxiliaries.insert(0, util)
