Import('*')

env.Clone()

env.Append(CPPPATH = ['.'])

env.CodeGenerate(
	target = 'u_format_table.c',
	script = 'u_format_table.py',
	source = ['u_format.csv'],
	command = 'python $SCRIPT $SOURCE > $TARGET'
)

env.CodeGenerate(
	target = 'u_format_access.c',
	script = 'u_format_access.py',
	source = ['u_format.csv'],
	command = 'python $SCRIPT $SOURCE > $TARGET'
)

util = env.ConvenienceLibrary(
	target = 'util',
	source = [
		'u_bitmask.c',
		'u_blit.c',
		'u_cache.c',
		'u_cpu_detect.c',
		'u_debug.c',
		'u_debug_dump.c',
		'u_debug_memory.c',
		'u_debug_stack.c',
		'u_debug_symbol.c',
		'u_draw_quad.c',
		'u_format.c',
		'u_format_access.c',
		'u_format_table.c',
		'u_gen_mipmap.c',
		'u_handle_table.c',
		'u_hash.c',
		'u_hash_table.c',
		'u_keymap.c',
		'u_network.c',
		'u_math.c',
		'u_mm.c',
		'u_rect.c',
		'u_simple_shaders.c',
		'u_snprintf.c',
		'u_stream_stdc.c',
		'u_stream_wd.c',
		'u_surface.c',
		'u_tile.c',
		'u_time.c',
		'u_timed_winsys.c',
		'u_upload_mgr.c',
		'u_simple_screen.c',
	])

auxiliaries.insert(0, util)
