Import('*')

env = env.Clone()

identity = env.ConvenienceLibrary(
	target = 'identity',
	source = env.ParseSourceList('Makefile.sources', 'C_SOURCES')
	)

env.Alias('identity', identity)

Export('identity')
