TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = draw

C_SOURCES = \
	draw_aaline.c \
	draw_aapoint.c \
	draw_clip.c \
	draw_vs_exec.c \
	draw_vs_sse.c \
	draw_vs_llvm.c \
	draw_context.c\
	draw_cull.c \
	draw_debug.c \
	draw_flatshade.c \
	draw_offset.c \
	draw_prim.c \
	draw_stipple.c \
	draw_twoside.c \
	draw_unfilled.c \
	draw_validate.c \
	draw_vbuf.c \
	draw_vertex.c \
	draw_vertex_cache.c \
	draw_vertex_fetch.c \
	draw_vertex_shader.c \
	draw_vf.c \
	draw_vf_generic.c \
	draw_vf_sse.c \
	draw_wide_prims.c

include ../../Makefile.template

symlinks:

