TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = draw

C_SOURCES = \
	draw_context.c \
	draw_pipe.c \
	draw_pipe_aaline.c \
	draw_pipe_aapoint.c \
	draw_pipe_clip.c \
	draw_pipe_cull.c \
	draw_pipe_flatshade.c \
	draw_pipe_offset.c \
	draw_pipe_pstipple.c \
	draw_pipe_stipple.c \
	draw_pipe_twoside.c \
	draw_pipe_unfilled.c \
	draw_pipe_util.c \
	draw_pipe_validate.c \
	draw_pipe_vbuf.c \
	draw_pipe_wide_line.c \
	draw_pipe_wide_point.c \
	draw_pt.c \
	draw_pt_elts.c \
	draw_pt_emit.c \
	draw_pt_fetch.c \
	draw_pt_fetch_emit.c \
	draw_pt_fetch_shade_emit.c \
	draw_pt_fetch_shade_pipeline.c \
	draw_pt_post_vs.c \
        draw_pt_util.c \
        draw_pt_varray.c \
	draw_pt_vcache.c \
	draw_vertex.c \
	draw_vs.c \
	draw_vs_varient.c \
	draw_vs_aos.c \
	draw_vs_aos_io.c \
	draw_vs_aos_machine.c \
	draw_vs_exec.c \
	draw_vs_llvm.c \
	draw_vs_sse.c 


include ../../Makefile.template

symlinks:

