Import('*')

draw = env.ConvenienceLibrary(
	target = 'draw',
	source = [
		'draw_aaline.c',
		'draw_aapoint.c',
		'draw_clip.c',
		'draw_context.c',
		'draw_cull.c',
		'draw_flatshade.c',
		'draw_offset.c',
		'draw_pstipple.c',
		'draw_pt.c',
		'draw_pt_elts.c',
		'draw_pt_emit.c',
		'draw_pt_fetch.c',
		'draw_pt_fetch_emit.c',
		'draw_pt_fetch_shade_pipeline.c',
		'draw_pt_pipeline.c',
		'draw_pt_post_vs.c',
		'draw_pt_vcache.c',
		'draw_stipple.c',
		'draw_twoside.c',
		'draw_unfilled.c',
		'draw_validate.c',
		'draw_vbuf.c',
		'draw_vertex.c',
		'draw_vertex_shader.c',
		'draw_vs_exec.c',
		'draw_vs_llvm.c',
		'draw_vs_sse.c',
		'draw_wide_line.c',
		'draw_wide_point.c',
	])

auxiliaries.insert(0, draw)
