Import('*')

draw = env.ConvenienceLibrary(
	target = 'draw',
	source = [
		'draw_aaline.c',
		'draw_aapoint.c',
		'draw_clip.c',
		'draw_vs_exec.c',
		'draw_vs_sse.c',
		'draw_vs_llvm.c',
		'draw_context.c',
		'draw_cull.c',
		'draw_debug.c',
		'draw_flatshade.c',
		'draw_offset.c',
		'draw_passthrough.c', # going away soon
		'draw_pt.c',
		'draw_pt_vcache.c',
		'draw_pt_fetch_emit.c',
		'draw_pt_elts.c',
		'draw_prim.c',
		'draw_pstipple.c',
		'draw_stipple.c',
		'draw_twoside.c',
		'draw_unfilled.c',
		'draw_validate.c',
		'draw_vbuf.c',
		'draw_vertex.c',
		'draw_vertex_cache.c',
		'draw_vertex_fetch.c',
		'draw_vertex_shader.c',
		'draw_vf.c',
		'draw_vf_generic.c',
		'draw_vf_sse.c',
		'draw_wide_point.c',
		'draw_wide_line.c'
	])

auxiliaries.insert(0, draw)
