TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv30

C_SOURCES = \
	nv30_context.c \
	nv30_draw.c \
	nv30_fragtex.c \
	nv30_screen.c \
	nv30_state.c \
	nv30_vbo.c \
	nv30_vertprog.c

LIBRARY_INCLUDES = -I$(TOP)/src/gallium/drivers/nvfx

include ../../Makefile.template
