TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = nv30

include Makefile.sources

LIBRARY_INCLUDES = \
	$(LIBDRM_CFLAGS)

include ../../Makefile.template
# DO NOT DELETE

# FIXME: Remove when this driver is converted to automake.
all: default
