# src/mesa/Makefile

TOP = ../..
include $(TOP)/configs/current

SRCDIR = .
include sources.mak

default:

######################################################################
# Installation rules

install: default $(DRICORE_INSTALL_TARGET)
	@for driver in $(DRIVER_DIRS) ; do \
	  case "$$driver" in \
	    osmesa) $(MAKE) -f Makefile.old install-osmesa || exit 1 ;; \
	  esac ; \
	done

install-osmesa: default
	$(MINSTALL) $(TOP)/$(LIB_DIR)/$(OSMESA_LIB_GLOB) \
		$(DESTDIR)$(INSTALL_LIB_DIR)

# Emacs tags
tags:
	etags `find . -name \*.[ch]` $(TOP)/include/GL/*.h
